static const unsigned char input[] =
	"shiny lime bags contain 3 muted magenta bags, 3 clear cyan bags.\nshiny violet bags contain 1 faded "
	"brown bag, 1 dull red bag.\nmuted maroon bags contain 4 pale lime bags.\npale magenta bags contain 2"
	" striped coral bags, 1 shiny orange bag, 3 vibrant white bags, 4 posh cyan bags.\nvibrant crimson ba"
	"gs contain 4 bright white bags, 3 dark brown bags, 4 plaid crimson bags.\nmirrored red bags contain "
	"2 bright orange bags, 3 dull brown bags, 4 dotted brown bags.\nmuted red bags contain 2 bright green"
	" bags.\nfaded chartreuse bags contain 5 bright cyan bags.\nwavy red bags contain 4 drab white bags, "
	"1 plaid silver bag.\npale purple bags contain 4 muted yellow bags, 2 mirrored chartreuse bags, 5 mir"
	"rored purple bags, 2 mirrored red bags.\ndull blue bags contain 4 dark brown bags, 2 faded blue bags"
	", 4 dim aqua bags.\nmirrored tomato bags contain 1 posh turquoise bag, 2 bright aqua bags.\nclear la"
	"vender bags contain 3 plaid bronze bags, 4 faded plum bags, 2 muted coral bags, 1 posh chartreuse ba"
	"g.\nlight cyan bags contain 1 plaid tan bag, 2 muted cyan bags, 3 dim cyan bags, 1 pale gray bag.\np"
	"laid lavender bags contain 4 bright cyan bags, 1 dim aqua bag, 3 muted orange bags.\ndotted bronze b"
	"ags contain 5 drab lime bags, 3 striped plum bags, 3 faded blue bags, 5 faded purple bags.\nclear in"
	"digo bags contain 3 dotted purple bags.\nvibrant cyan bags contain 4 dim tomato bags, 1 dull green b"
	"ag, 5 light silver bags, 2 striped gold bags.\npale yellow bags contain no other bags.\ndrab gray ba"
	"gs contain 4 shiny maroon bags.\nclear turquoise bags contain 3 dotted blue bags, 3 faded cyan bags."
	"\nplaid bronze bags contain 3 light tomato bags, 2 faded chartreuse bags.\nmirrored turquoise bags c"
	"ontain 2 plaid purple bags, 5 mirrored tomato bags, 2 drab tan bags.\nwavy turquoise bags contain 2 "
	"plaid salmon bags.\nshiny yellow bags contain 2 striped aqua bags, 5 drab gray bags, 4 pale aqua bag"
	"s, 5 dim purple bags.\nclear magenta bags contain 1 striped brown bag, 1 dull black bag, 5 light lim"
	"e bags.\nplaid indigo bags contain 5 wavy purple bags, 2 pale blue bags.\nplaid brown bags contain 4"
	" striped salmon bags.\ndull gold bags contain 2 mirrored green bags, 1 shiny coral bag, 4 shiny red "
	"bags.\ndark white bags contain 3 muted black bags, 1 vibrant yellow bag, 4 dotted chartreuse bags, 3"
	" mirrored white bags.\ndrab blue bags contain 3 wavy tomato bags.\ndull teal bags contain 5 drab fuc"
	"hsia bags, 4 dim black bags.\ndrab aqua bags contain 3 dark red bags.\nfaded gold bags contain 1 pal"
	"e bronze bag, 4 dim gold bags, 1 vibrant aqua bag, 2 bright aqua bags.\ndrab black bags contain 3 li"
	"ght cyan bags.\ndim purple bags contain 5 mirrored bronze bags, 3 shiny bronze bags, 3 shiny turquoi"
	"se bags, 4 clear maroon bags.\ndim lime bags contain 4 vibrant yellow bags.\ndotted white bags conta"
	"in 5 faded lime bags.\nmuted lavender bags contain 3 dotted bronze bags, 2 faded chartreuse bags, 5 "
	"drab gold bags, 5 dark white bags.\ndrab white bags contain 1 clear lavender bag, 3 posh maroon bags"
	".\nbright tan bags contain 5 mirrored gray bags, 4 posh plum bags, 4 dull brown bags.\npale beige ba"
	"gs contain 4 muted indigo bags.\nbright turquoise bags contain 5 wavy violet bags, 4 wavy indigo bag"
	"s, 2 faded beige bags, 2 dim yellow bags.\nmuted violet bags contain 4 drab lime bags.\nposh chartre"
	"use bags contain 5 wavy silver bags, 4 light aqua bags.\nfaded green bags contain 5 muted magenta ba"
	"gs, 4 dark fuchsia bags.\ndull orange bags contain 2 mirrored tomato bags, 4 wavy orange bags.\nposh"
	" red bags contain 5 dim chartreuse bags, 1 shiny aqua bag, 1 wavy black bag.\nclear crimson bags con"
	"tain 5 dotted tan bags, 2 wavy crimson bags, 4 dim orange bags, 5 drab turquoise bags.\nstriped lave"
	"nder bags contain 5 plaid teal bags, 4 dull crimson bags, 4 posh lavender bags.\nfaded lavender bags"
	" contain 2 vibrant coral bags.\nposh lavender bags contain 2 drab silver bags, 1 drab cyan bag.\npla"
	"id olive bags contain 5 vibrant yellow bags, 1 striped bronze bag.\nlight indigo bags contain 3 shin"
	"y cyan bags, 3 vibrant yellow bags.\nlight orange bags contain 2 dark indigo bags.\ndim teal bags co"
	"ntain 3 bright lavender bags, 4 wavy tomato bags, 2 shiny gray bags, 5 bright blue bags.\ndull tomat"
	"o bags contain 5 drab lime bags, 3 dark olive bags, 4 drab turquoise bags.\nmuted indigo bags contai"
	"n 5 posh chartreuse bags, 1 mirrored green bag, 3 dark brown bags, 1 dark orange bag.\nwavy fuchsia "
	"bags contain 3 mirrored magenta bags, 5 drab fuchsia bags, 5 dull green bags.\ndim violet bags conta"
	"in 2 posh crimson bags.\nfaded lime bags contain no other bags.\nwavy salmon bags contain 5 posh red"
	" bags.\ndrab cyan bags contain 3 dull indigo bags, 1 vibrant indigo bag.\nstriped purple bags contai"
	"n 1 faded blue bag, 3 faded fuchsia bags, 3 pale maroon bags.\ndim aqua bags contain no other bags.\n"
	"pale olive bags contain 1 muted indigo bag.\nstriped tan bags contain 4 light coral bags, 4 dull vio"
	"let bags, 3 dim purple bags, 5 dull yellow bags.\ndull black bags contain 1 dotted beige bag.\nbrigh"
	"t lime bags contain 2 light yellow bags.\nfaded red bags contain 2 drab teal bags, 2 pale coral bags"
	", 5 dotted black bags.\nvibrant green bags contain 4 drab bronze bags.\nposh gold bags contain 2 pal"
	"e cyan bags, 3 clear lavender bags, 2 plaid bronze bags.\nmuted magenta bags contain 5 shiny blue ba"
	"gs, 1 faded olive bag, 4 drab brown bags, 3 dull violet bags.\nmuted lime bags contain 5 light blue "
	"bags, 1 vibrant lavender bag.\nmuted tan bags contain 3 vibrant coral bags, 5 muted coral bags, 3 li"
	"ght bronze bags.\ndrab teal bags contain 3 dotted fuchsia bags, 4 drab aqua bags, 3 dim aqua bags.\n"
	"muted purple bags contain 1 drab tan bag.\ndim brown bags contain 4 dotted tan bags.\ndrab lime bags"
	" contain 1 mirrored green bag, 5 clear lime bags, 3 posh yellow bags, 5 pale yellow bags.\nwavy aqua"
	" bags contain 1 faded silver bag.\nstriped magenta bags contain 2 mirrored aqua bags, 1 dotted gold "
	"bag.\ndull maroon bags contain 2 drab maroon bags, 3 shiny lavender bags.\ndotted yellow bags contai"
	"n 2 dark indigo bags, 3 shiny gold bags, 2 muted coral bags, 5 pale maroon bags.\nshiny plum bags co"
	"ntain 5 vibrant coral bags, 3 dotted gray bags, 1 pale lime bag, 4 plaid green bags.\nfaded violet b"
	"ags contain 1 dark crimson bag, 5 pale gray bags, 1 pale olive bag.\nfaded olive bags contain 4 wavy"
	" indigo bags.\ndrab green bags contain 1 vibrant yellow bag, 1 posh tomato bag, 1 dull yellow bag, 5"
	" shiny bronze bags.\nshiny black bags contain 3 clear gray bags, 4 dim tomato bags.\ndull coral bags"
	" contain 1 pale cyan bag, 1 light brown bag.\nmirrored coral bags contain 1 dark tomato bag, 3 vibra"
	"nt coral bags, 3 posh lime bags, 3 pale fuchsia bags.\nfaded white bags contain 1 light silver bag, "
	"3 striped turquoise bags, 3 dark green bags, 3 posh orange bags.\nwavy orange bags contain 2 dotted "
	"indigo bags, 1 vibrant indigo bag, 4 dull teal bags, 3 striped gold bags.\nplaid beige bags contain "
	"4 pale blue bags.\nplaid green bags contain 1 mirrored bronze bag, 3 mirrored purple bags, 5 shiny c"
	"oral bags, 5 posh yellow bags.\nmirrored tan bags contain 1 faded blue bag.\nplaid violet bags conta"
	"in 2 faded blue bags.\nshiny coral bags contain 3 vibrant bronze bags, 5 dull salmon bags.\ndim beig"
	"e bags contain 3 plaid magenta bags, 2 light gold bags, 1 shiny blue bag, 5 bright teal bags.\npale "
	"coral bags contain 1 faded orange bag, 3 dark turquoise bags.\nmirrored crimson bags contain 2 dull "
	"silver bags.\ndim tan bags contain 3 light tomato bags, 4 dotted chartreuse bags.\nstriped cyan bags"
	" contain 1 faded violet bag, 3 dotted lavender bags, 4 light lavender bags, 1 drab fuchsia bag.\ndul"
	"l turquoise bags contain 3 bright teal bags, 1 faded blue bag, 5 bright magenta bags.\nbright magent"
	"a bags contain 2 wavy indigo bags.\nwavy magenta bags contain 2 dim cyan bags, 2 dim violet bags, 4 "
	"dark salmon bags, 2 vibrant bronze bags.\nwavy lavender bags contain 4 pale cyan bags, 4 vibrant yel"
	"low bags, 1 vibrant white bag.\npale green bags contain 3 dark indigo bags, 3 shiny gray bags.\ndark"
	" aqua bags contain 3 faded turquoise bags, 3 vibrant indigo bags, 3 dull salmon bags, 1 dotted gray "
	"bag.\ndim gray bags contain 1 faded silver bag, 3 muted red bags, 2 wavy orange bags, 1 posh beige b"
	"ag.\nclear black bags contain 4 vibrant plum bags, 3 bright brown bags, 2 dark gray bags, 1 clear te"
	"al bag.\ndrab indigo bags contain 2 dim aqua bags, 5 vibrant blue bags, 5 dull salmon bags, 5 drab v"
	"iolet bags.\nmirrored orange bags contain 5 posh olive bags, 5 dotted tan bags, 5 mirrored salmon ba"
	"gs, 4 posh red bags.\nplaid fuchsia bags contain 4 drab green bags, 3 mirrored tomato bags, 5 light "
	"white bags, 5 muted cyan bags.\nshiny teal bags contain 5 bright white bags, 5 mirrored red bags.\nl"
	"ight maroon bags contain 1 drab cyan bag.\nvibrant fuchsia bags contain 5 drab crimson bags.\nfaded "
	"gray bags contain 3 mirrored aqua bags.\nwavy chartreuse bags contain 4 muted orange bags, 2 clear b"
	"lue bags, 1 muted tan bag, 2 clear lime bags.\ndark yellow bags contain 5 wavy orange bags, 4 mirror"
	"ed beige bags.\nwavy green bags contain 5 vibrant tan bags.\ndotted magenta bags contain 2 shiny red"
	" bags.\nfaded crimson bags contain 4 muted gray bags, 3 dim black bags.\ndull cyan bags contain 3 po"
	"sh tomato bags, 3 drab indigo bags, 2 vibrant blue bags.\nposh aqua bags contain 2 posh yellow bags."
	"\nmuted white bags contain 1 faded tomato bag.\nvibrant tomato bags contain 5 vibrant white bags.\nd"
	"im black bags contain 2 drab indigo bags.\nmirrored lime bags contain 4 dull brown bags.\ndrab plum "
	"bags contain 5 plaid green bags, 5 striped lime bags, 1 dotted teal bag.\ndark olive bags contain 2 "
	"wavy plum bags.\npale lime bags contain 4 dark orange bags, 5 dim black bags, 1 dull white bag.\nstr"
	"iped fuchsia bags contain 4 bright orange bags, 3 pale maroon bags.\nplaid maroon bags contain 1 dul"
	"l coral bag.\nclear white bags contain 5 plaid lavender bags, 1 faded turquoise bag, 1 mirrored toma"
	"to bag, 5 faded silver bags.\ndark tan bags contain 4 striped gold bags.\nmuted beige bags contain 3"
	" dark gold bags.\nfaded cyan bags contain 5 vibrant yellow bags, 2 shiny plum bags.\ndrab beige bags"
	" contain 4 dotted orange bags, 2 dark black bags, 2 bright olive bags, 4 dark gold bags.\ndrab turqu"
	"oise bags contain 2 clear blue bags, 2 muted cyan bags, 4 faded turquoise bags.\nstriped green bags "
	"contain 4 striped plum bags, 5 dark gold bags.\nbright coral bags contain 4 posh teal bags, 3 shiny "
	"crimson bags, 5 dim magenta bags.\nplaid plum bags contain 5 wavy teal bags, 3 mirrored beige bags, "
	"3 faded silver bags.\ndrab red bags contain 3 light magenta bags, 1 drab salmon bag, 4 shiny tan bag"
	"s.\ndotted coral bags contain 1 faded black bag.\nwavy coral bags contain 2 posh white bags, 1 shiny"
	" gold bag, 1 striped aqua bag.\nbright aqua bags contain 1 dotted olive bag, 1 striped gold bag.\nbr"
	"ight purple bags contain 1 vibrant purple bag, 2 clear orange bags.\nvibrant lime bags contain 1 dot"
	"ted turquoise bag, 5 dotted magenta bags, 5 light black bags.\npale indigo bags contain 5 vibrant ch"
	"artreuse bags, 5 clear white bags, 1 light lime bag, 3 dull silver bags.\ndull bronze bags contain 4"
	" dark indigo bags, 3 plaid bronze bags, 2 pale yellow bags.\nwavy plum bags contain 5 bright chartre"
	"use bags, 5 pale maroon bags, 1 clear lime bag.\ndull purple bags contain 4 muted gray bags.\ndrab b"
	"rown bags contain 3 drab lime bags, 3 dull silver bags, 2 dark gold bags, 3 drab beige bags.\ndotted"
	" crimson bags contain 1 dotted black bag.\nbright violet bags contain 5 dull olive bags, 2 striped t"
	"urquoise bags, 3 vibrant aqua bags, 4 clear maroon bags.\ndark fuchsia bags contain 2 wavy purple ba"
	"gs, 4 pale tan bags, 2 vibrant coral bags, 5 dark brown bags.\nwavy maroon bags contain 2 striped fu"
	"chsia bags.\nlight white bags contain 2 dull green bags.\ndotted indigo bags contain 2 clear lavende"
	"r bags, 4 shiny coral bags.\nshiny turquoise bags contain 1 posh crimson bag, 1 posh salmon bag, 4 v"
	"ibrant bronze bags.\ndull fuchsia bags contain 1 mirrored red bag, 3 posh gray bags, 4 plaid maroon "
	"bags, 4 clear gold bags.\nlight magenta bags contain 3 plaid tan bags.\nfaded beige bags contain 5 b"
	"right indigo bags, 1 pale yellow bag, 2 vibrant yellow bags.\nmirrored gold bags contain 1 mirrored "
	"blue bag, 2 posh fuchsia bags, 5 dark red bags.\nlight salmon bags contain 5 muted black bags, 5 dul"
	"l blue bags, 2 light aqua bags, 1 pale tomato bag.\nwavy gray bags contain 3 light red bags.\nbright"
	" gray bags contain 4 dotted blue bags.\npale white bags contain 3 drab aqua bags, 3 wavy maroon bags"
	", 4 shiny blue bags, 4 dotted lime bags.\ndim turquoise bags contain 3 striped crimson bags, 2 faded"
	" silver bags.\nclear silver bags contain 4 plaid gray bags, 1 dark black bag.\nbright brown bags con"
	"tain 5 faded chartreuse bags.\nmuted olive bags contain 1 dotted red bag, 1 posh green bag.\nstriped"
	" silver bags contain 3 dotted tomato bags, 1 plaid cyan bag, 4 clear white bags, 5 mirrored indigo b"
	"ags.\ndrab yellow bags contain 5 wavy silver bags, 5 dark orange bags, 3 dark brown bags, 2 bright m"
	"agenta bags.\nvibrant red bags contain 5 vibrant bronze bags, 2 posh tomato bags, 3 dull lime bags, "
	"2 striped violet bags.\ndotted maroon bags contain 2 vibrant silver bags.\nfaded teal bags contain 4"
	" clear lavender bags.\ndim crimson bags contain 1 faded chartreuse bag.\nfaded orange bags contain 3"
	" bright magenta bags, 4 mirrored brown bags.\ndotted lime bags contain 4 light brown bags, 1 bright "
	"white bag, 5 dim lime bags.\nposh turquoise bags contain 4 striped indigo bags, 2 dim white bags.\nd"
	"ark beige bags contain 1 dark olive bag.\ndotted black bags contain 2 posh turquoise bags, 3 wavy in"
	"digo bags, 4 dotted violet bags.\ndotted fuchsia bags contain 5 dark black bags, 1 clear lime bag.\n"
	"plaid magenta bags contain 3 posh maroon bags, 4 drab green bags.\nmuted coral bags contain 5 light "
	"brown bags, 2 posh chartreuse bags, 1 vibrant tan bag.\nstriped yellow bags contain 1 light brown ba"
	"g.\nposh violet bags contain 3 bright magenta bags.\ndark brown bags contain 2 faded blue bags, 2 di"
	"m aqua bags, 5 posh yellow bags, 5 drab violet bags.\ndrab fuchsia bags contain 3 shiny aqua bags, 2"
	" plaid lavender bags, 1 muted cyan bag.\nstriped maroon bags contain 4 clear lime bags, 5 striped go"
	"ld bags, 3 clear plum bags, 3 dull tan bags.\nmuted yellow bags contain 1 shiny turquoise bag.\nbrig"
	"ht silver bags contain 5 striped red bags, 4 dark aqua bags.\nlight beige bags contain 1 shiny gold "
	"bag, 4 dark orange bags.\nlight coral bags contain 3 clear beige bags, 4 shiny maroon bags.\nplaid c"
	"yan bags contain 4 pale yellow bags, 1 drab beige bag, 1 bright chartreuse bag, 1 clear coral bag.\n"
	"shiny tomato bags contain 3 muted indigo bags, 2 faded indigo bags.\ndark maroon bags contain 1 posh"
	" white bag, 2 wavy aqua bags, 5 muted brown bags.\nplaid teal bags contain 1 dull lime bag, 3 faded "
	"blue bags, 4 drab cyan bags, 3 clear cyan bags.\nvibrant magenta bags contain 2 wavy tan bags.\npale"
	" tomato bags contain 2 bright silver bags, 1 dull teal bag, 5 dull lime bags, 5 muted aqua bags.\ndi"
	"m orange bags contain 1 vibrant white bag, 5 bright tomato bags.\nplaid crimson bags contain 2 wavy "
	"brown bags, 2 striped maroon bags, 4 dark magenta bags.\nposh beige bags contain 1 faded blue bag.\n"
	"dotted gray bags contain 3 drab silver bags, 4 faded silver bags, 2 light coral bags.\nshiny blue ba"
	"gs contain 1 bright magenta bag.\npale gold bags contain 1 light coral bag, 5 vibrant aqua bags, 2 w"
	"avy plum bags, 5 dim lavender bags.\nstriped chartreuse bags contain 3 wavy bronze bags.\nvibrant la"
	"vender bags contain 3 clear bronze bags, 4 dull yellow bags.\ndrab tomato bags contain 1 mirrored aq"
	"ua bag, 3 drab yellow bags, 2 muted white bags.\nvibrant brown bags contain 3 pale white bags.\ndark"
	" salmon bags contain 3 dull salmon bags, 5 drab violet bags, 4 striped indigo bags.\ndotted tomato b"
	"ags contain 5 muted fuchsia bags, 3 pale aqua bags, 1 dim aqua bag, 3 dull yellow bags.\nwavy gold b"
	"ags contain 2 light aqua bags, 3 dull white bags.\npale salmon bags contain 2 dotted lime bags, 2 sh"
	"iny gold bags.\nbright cyan bags contain no other bags.\nclear maroon bags contain 3 mirrored white "
	"bags, 5 faded blue bags, 3 drab yellow bags, 4 light aqua bags.\ndull indigo bags contain 3 vibrant "
	"indigo bags, 4 pale yellow bags.\nplaid black bags contain 2 faded orange bags, 2 drab aqua bags.\ns"
	"triped salmon bags contain 5 drab violet bags, 3 dark brown bags, 4 dull white bags, 4 clear lime ba"
	"gs.\nwavy bronze bags contain 4 wavy silver bags, 4 light bronze bags, 2 shiny coral bags.\ndull lim"
	"e bags contain 1 dull green bag, 3 dark orange bags, 4 shiny maroon bags.\ndrab chartreuse bags cont"
	"ain 2 clear lime bags, 3 dim cyan bags, 3 faded cyan bags.\ndotted lavender bags contain 5 dull indi"
	"go bags.\nstriped aqua bags contain 4 dotted lime bags, 4 dotted brown bags.\nplaid gold bags contai"
	"n 2 dim lime bags, 1 dull bronze bag, 5 faded fuchsia bags, 2 drab yellow bags.\nfaded coral bags co"
	"ntain 1 vibrant green bag, 1 drab yellow bag, 4 wavy teal bags.\nfaded bronze bags contain 2 dim lim"
	"e bags, 4 wavy magenta bags.\nstriped turquoise bags contain 5 mirrored magenta bags.\nplaid yellow "
	"bags contain 4 mirrored maroon bags, 1 dim silver bag, 3 striped gold bags.\nvibrant coral bags cont"
	"ain 2 mirrored white bags, 1 dull lime bag.\nposh black bags contain 3 clear beige bags, 2 drab gold"
	" bags, 3 mirrored indigo bags, 1 dim black bag.\nwavy beige bags contain 1 vibrant purple bag, 4 lig"
	"ht green bags, 3 light red bags.\npale blue bags contain no other bags.\nlight silver bags contain 1"
	" posh chartreuse bag, 5 vibrant tan bags.\nmirrored teal bags contain 1 dark tomato bag, 1 wavy teal"
	" bag, 3 vibrant maroon bags, 5 pale red bags.\npale gray bags contain 3 mirrored bronze bags, 3 fade"
	"d crimson bags, 3 dotted red bags, 2 striped yellow bags.\nvibrant chartreuse bags contain 4 mirrore"
	"d yellow bags.\nclear gold bags contain 1 bright magenta bag, 3 dotted olive bags, 2 posh yellow bag"
	"s, 2 dull blue bags.\nwavy tomato bags contain 3 shiny coral bags, 4 posh chartreuse bags, 2 light a"
	"qua bags, 3 dark orange bags.\nposh yellow bags contain 5 vibrant bronze bags, 5 faded lime bags, 4 "
	"posh chartreuse bags, 2 bright cyan bags.\ndark lime bags contain 3 drab tomato bags.\npale crimson "
	"bags contain 2 pale maroon bags, 5 clear lime bags.\nmirrored beige bags contain 5 clear maroon bags"
	", 2 wavy maroon bags, 2 drab indigo bags.\nlight lime bags contain 1 light bronze bag.\nvibrant silv"
	"er bags contain 4 pale tan bags.\ndull plum bags contain 3 vibrant yellow bags, 1 striped plum bag, "
	"2 dim aqua bags.\nmirrored chartreuse bags contain 3 wavy black bags.\nplaid white bags contain 5 da"
	"rk aqua bags, 1 muted orange bag.\nbright fuchsia bags contain 5 vibrant tan bags.\ndrab gold bags c"
	"ontain 1 faded blue bag.\nbright tomato bags contain 1 dim white bag, 1 drab yellow bag.\ndotted cha"
	"rtreuse bags contain 4 dim aqua bags.\nfaded fuchsia bags contain 2 light tomato bags, 1 posh yellow"
	" bag, 4 faded chartreuse bags, 1 pale blue bag.\npale silver bags contain 1 drab orange bag, 5 clear"
	" salmon bags, 2 plaid violet bags.\nmirrored purple bags contain 4 clear lime bags.\nmirrored green "
	"bags contain 4 dim aqua bags.\nvibrant violet bags contain 3 dark orange bags.\nplaid blue bags cont"
	"ain 4 striped crimson bags, 2 vibrant lavender bags, 4 faded plum bags, 5 dull salmon bags.\nmuted o"
	"range bags contain 1 bright indigo bag, 4 posh yellow bags, 4 bright cyan bags.\nvibrant blue bags c"
	"ontain no other bags.\nlight gray bags contain 2 striped green bags, 3 clear blue bags, 3 shiny cora"
	"l bags.\ndark plum bags contain 2 faded crimson bags, 2 dark salmon bags, 2 shiny gray bags.\ndrab v"
	"iolet bags contain no other bags.\ndim chartreuse bags contain 3 dotted brown bags, 5 faded plum bag"
	"s, 4 wavy tomato bags.\nwavy cyan bags contain 5 faded aqua bags, 1 striped blue bag, 5 posh olive b"
	"ags.\nclear teal bags contain 1 mirrored olive bag, 5 dim tomato bags.\nlight violet bags contain 2 "
	"posh gray bags, 5 dotted cyan bags.\ndark tomato bags contain 5 plaid white bags, 1 wavy indigo bag."
	"\nwavy purple bags contain 3 drab green bags.\npale black bags contain 3 drab indigo bags.\ndrab ora"
	"nge bags contain 5 striped turquoise bags.\nmirrored white bags contain 4 dim aqua bags.\nlight purp"
	"le bags contain 2 wavy green bags, 5 bright brown bags, 5 muted crimson bags, 3 dotted purple bags.\n"
	"shiny orange bags contain 2 muted indigo bags.\nbright green bags contain 3 mirrored tomato bags, 3 "
	"dim bronze bags.\nlight black bags contain 4 dotted yellow bags, 3 dark turquoise bags, 3 vibrant bl"
	"ue bags, 4 clear maroon bags.\nshiny fuchsia bags contain 1 clear cyan bag, 1 striped silver bag, 2 "
	"bright black bags.\nstriped bronze bags contain 1 dotted lime bag, 4 dark chartreuse bags, 3 shiny b"
	"ronze bags.\nlight tomato bags contain 5 dull salmon bags.\ndrab crimson bags contain 3 clear coral "
	"bags, 5 drab bronze bags, 3 clear black bags, 2 pale maroon bags.\nvibrant aqua bags contain 2 dark "
	"black bags, 2 mirrored green bags.\nclear bronze bags contain 2 mirrored aqua bags, 4 dark green bag"
	"s, 5 dotted red bags.\nbright chartreuse bags contain 1 dim lime bag.\nmirrored fuchsia bags contain"
	" 1 faded chartreuse bag, 3 pale olive bags, 4 pale cyan bags, 2 muted beige bags.\ndim plum bags con"
	"tain 5 dotted bronze bags, 2 drab yellow bags, 5 shiny blue bags, 5 dotted cyan bags.\ndark indigo b"
	"ags contain 4 dark brown bags, 2 dull cyan bags, 4 faded chartreuse bags.\npale fuchsia bags contain"
	" 1 dim purple bag, 5 dark gray bags, 2 dim brown bags, 3 wavy tomato bags.\ndull green bags contain "
	"2 dark brown bags, 4 drab indigo bags, 1 mirrored green bag, 2 drab lime bags.\ndotted aqua bags con"
	"tain 2 plaid lavender bags.\nstriped white bags contain 2 drab cyan bags.\ndim maroon bags contain 5"
	" dull indigo bags, 3 pale aqua bags.\nshiny olive bags contain 2 wavy aqua bags, 4 mirrored crimson "
	"bags.\ndotted blue bags contain 4 bright brown bags, 5 dotted black bags, 2 faded teal bags, 3 pale "
	"yellow bags.\nplaid salmon bags contain 5 dull purple bags, 4 faded lime bags, 2 striped aqua bags.\n"
	"dotted gold bags contain 4 bright black bags.\ndark black bags contain 2 dull blue bags.\nposh cyan "
	"bags contain 5 shiny yellow bags.\nposh green bags contain 4 plaid beige bags.\ndim fuchsia bags con"
	"tain 1 dull salmon bag, 1 dull olive bag, 5 shiny yellow bags.\nwavy brown bags contain 1 clear plum"
	" bag.\nplaid red bags contain 1 dim indigo bag, 4 muted blue bags.\nlight chartreuse bags contain 1 "
	"dotted yellow bag, 4 clear gold bags, 1 bright magenta bag, 5 dark tan bags.\nvibrant white bags con"
	"tain 1 muted gray bag.\nlight red bags contain 1 dark bronze bag, 3 shiny lavender bags.\nlight bron"
	"ze bags contain 1 wavy silver bag, 3 plaid lavender bags, 4 drab violet bags, 5 mirrored green bags."
	"\ndark magenta bags contain 5 pale aqua bags.\nstriped gray bags contain 1 posh cyan bag.\ndark cyan"
	" bags contain 2 drab fuchsia bags, 1 clear cyan bag, 2 plaid gold bags.\nplaid silver bags contain 3"
	" bright beige bags.\nshiny gray bags contain 2 dull blue bags, 2 faded chartreuse bags.\nshiny cyan "
	"bags contain 1 striped salmon bag, 4 vibrant tan bags.\nplaid gray bags contain 5 wavy aqua bags, 5 "
	"vibrant yellow bags, 1 mirrored indigo bag, 1 faded silver bag.\ndrab salmon bags contain 2 muted aq"
	"ua bags.\nposh gray bags contain 3 posh tan bags, 4 wavy indigo bags, 5 dark gray bags.\nshiny brown"
	" bags contain 3 muted gray bags, 2 muted tomato bags.\ndrab maroon bags contain 1 bright chartreuse "
	"bag, 2 dark aqua bags, 3 dim black bags, 5 wavy silver bags.\nlight yellow bags contain 5 striped pu"
	"rple bags, 1 faded fuchsia bag, 2 plaid gold bags, 2 dotted olive bags.\nclear salmon bags contain 3"
	" faded chartreuse bags, 5 posh salmon bags, 5 mirrored red bags.\nbright orange bags contain 2 posh "
	"tomato bags.\nclear purple bags contain 3 dim olive bags, 2 mirrored violet bags, 1 muted tomato bag"
	".\ndull brown bags contain 2 faded lime bags, 5 drab violet bags, 1 mirrored green bag.\nvibrant sal"
	"mon bags contain 5 muted green bags, 4 faded bronze bags, 1 vibrant indigo bag.\ndull silver bags co"
	"ntain 2 light green bags.\nvibrant beige bags contain 2 dull cyan bags.\nmuted salmon bags contain 3"
	" bright aqua bags, 2 pale maroon bags, 1 light aqua bag.\nclear tomato bags contain 5 clear lavender"
	" bags, 4 dull tan bags, 2 dotted turquoise bags.\nstriped brown bags contain 3 drab lavender bags, 5"
	" clear lavender bags.\ndotted turquoise bags contain 1 light tan bag, 2 dull tomato bags.\nposh oran"
	"ge bags contain 1 mirrored cyan bag, 3 shiny cyan bags, 5 bright beige bags, 4 striped lime bags.\nd"
	"ull olive bags contain 5 light silver bags, 3 wavy olive bags, 3 bright magenta bags, 4 mirrored bro"
	"nze bags.\nposh maroon bags contain 2 striped violet bags, 3 plaid lavender bags, 2 clear beige bags"
	".\npale chartreuse bags contain 1 faded lime bag, 2 light aqua bags, 1 muted coral bag.\ndim magenta"
	" bags contain 1 faded chartreuse bag.\nstriped tomato bags contain 5 plaid lavender bags, 1 posh bei"
	"ge bag, 1 clear lavender bag, 4 muted indigo bags.\nshiny aqua bags contain 1 wavy gold bag, 1 plaid"
	" gold bag.\nposh magenta bags contain 3 shiny beige bags, 3 clear gold bags.\nmuted black bags conta"
	"in 5 dull yellow bags, 4 faded beige bags.\nplaid tomato bags contain 3 dotted crimson bags, 3 shiny"
	" tan bags.\ndim red bags contain 4 light beige bags, 5 shiny gold bags, 5 posh blue bags, 4 dotted i"
	"ndigo bags.\ndrab lavender bags contain 4 striped indigo bags, 3 vibrant tan bags, 3 plaid aqua bags"
	", 3 plaid bronze bags.\nvibrant orange bags contain 3 dotted lavender bags, 1 posh purple bag, 5 dul"
	"l cyan bags.\nlight lavender bags contain 4 drab cyan bags, 5 posh maroon bags, 3 dotted red bags.\n"
	"dark red bags contain 4 faded plum bags.\nplaid chartreuse bags contain 1 posh blue bag.\nclear tan "
	"bags contain 2 dull purple bags, 2 plaid purple bags.\nmuted bronze bags contain 2 plaid salmon bags"
	", 2 muted crimson bags, 4 dotted olive bags.\npale lavender bags contain 1 vibrant plum bag, 5 vibra"
	"nt yellow bags.\nposh crimson bags contain 2 light brown bags.\ndark blue bags contain 5 mirrored to"
	"mato bags, 1 drab coral bag, 3 wavy purple bags.\ndim silver bags contain 5 drab yellow bags, 5 posh"
	" purple bags, 3 light tomato bags, 3 wavy blue bags.\nfaded maroon bags contain 3 dark salmon bags, "
	"3 faded aqua bags, 1 clear olive bag, 2 clear brown bags.\ndark bronze bags contain 3 dim white bags"
	", 3 bright cyan bags, 4 clear olive bags, 2 faded crimson bags.\npale orange bags contain 1 light ye"
	"llow bag, 5 bright olive bags, 2 pale olive bags.\nbright maroon bags contain 3 bright white bags, 1"
	" dotted orange bag.\ndull yellow bags contain 5 light bronze bags, 4 faded beige bags, 2 dark orange"
	" bags, 2 dull cyan bags.\nwavy violet bags contain 2 dim aqua bags, 5 posh chartreuse bags.\ndull be"
	"ige bags contain 1 shiny bronze bag, 1 striped crimson bag, 5 plaid indigo bags.\nclear yellow bags "
	"contain 3 dim brown bags, 4 dotted lavender bags.\nclear red bags contain 3 shiny indigo bags, 1 vib"
	"rant plum bag, 1 dim fuchsia bag, 5 striped teal bags.\ndotted silver bags contain 5 wavy bronze bag"
	"s, 4 vibrant cyan bags, 2 dull blue bags, 2 posh yellow bags.\nshiny maroon bags contain 3 muted ind"
	"igo bags, 5 light white bags, 3 posh yellow bags, 4 posh tomato bags.\ndark lavender bags contain 1 "
	"vibrant tan bag, 5 plaid lime bags.\nvibrant plum bags contain 1 faded teal bag, 5 shiny plum bags, "
	"3 bright fuchsia bags, 1 shiny coral bag.\nbright beige bags contain 2 mirrored green bags.\nclear b"
	"eige bags contain 1 posh chartreuse bag, 4 drab cyan bags, 3 light beige bags.\nmirrored yellow bags"
	" contain 3 faded beige bags, 2 shiny cyan bags, 2 wavy silver bags, 2 dull yellow bags.\nshiny laven"
	"der bags contain 4 clear cyan bags.\nmuted cyan bags contain 5 posh tomato bags, 2 drab gray bags, 1"
	" dull indigo bag, 3 pale blue bags.\nlight teal bags contain 3 dull yellow bags, 2 striped fuchsia b"
	"ags.\nvibrant black bags contain 3 bright white bags.\nlight turquoise bags contain 4 muted indigo b"
	"ags, 3 mirrored silver bags, 5 dark tomato bags.\nlight gold bags contain 5 mirrored magenta bags.\n"
	"dull lavender bags contain 2 wavy chartreuse bags, 3 dull crimson bags, 3 pale tomato bags.\nlight o"
	"live bags contain 4 dark orange bags, 4 clear olive bags.\npale red bags contain 3 plaid lavender ba"
	"gs, 4 plaid beige bags, 1 plaid coral bag, 1 shiny chartreuse bag.\nwavy lime bags contain 2 muted c"
	"oral bags, 2 clear teal bags, 3 dull maroon bags, 4 dim lime bags.\npale bronze bags contain 4 vibra"
	"nt cyan bags.\nwavy tan bags contain 3 drab lavender bags, 2 dotted aqua bags, 2 bright white bags.\n"
	"faded aqua bags contain 4 wavy black bags.\nmirrored maroon bags contain 2 bright white bags, 4 dott"
	"ed maroon bags, 5 light coral bags, 5 striped turquoise bags.\nstriped teal bags contain 4 bright ch"
	"artreuse bags, 3 striped indigo bags, 5 dark lavender bags, 4 posh white bags.\nstriped coral bags c"
	"ontain 2 striped lime bags, 2 wavy purple bags, 1 striped plum bag.\nmirrored brown bags contain 1 f"
	"aded lime bag, 5 drab indigo bags, 4 bright white bags.\nfaded tomato bags contain 1 dim indigo bag,"
	" 5 shiny plum bags, 1 drab yellow bag, 4 drab indigo bags.\nshiny tan bags contain 3 dark turquoise "
	"bags, 3 muted aqua bags.\nposh tomato bags contain no other bags.\nclear chartreuse bags contain 4 s"
	"hiny indigo bags, 2 dim cyan bags.\nbright olive bags contain 2 faded blue bags.\ndull tan bags cont"
	"ain 4 striped red bags.\nmuted aqua bags contain 3 dark black bags, 4 faded crimson bags, 2 plaid wh"
	"ite bags, 3 bright black bags.\nshiny red bags contain 1 dull blue bag, 2 bright white bags.\nbright"
	" white bags contain 2 faded blue bags.\ndotted salmon bags contain 1 dotted indigo bag.\nfaded turqu"
	"oise bags contain 5 dark orange bags.\nposh plum bags contain 5 faded white bags.\nwavy olive bags c"
	"ontain 5 light aqua bags, 1 pale lavender bag, 5 pale green bags.\nlight crimson bags contain 1 mute"
	"d indigo bag, 2 plaid beige bags.\nmirrored gray bags contain 1 posh lavender bag, 5 wavy indigo bag"
	"s, 4 dotted crimson bags.\nstriped crimson bags contain 2 striped salmon bags, 5 mirrored magenta ba"
	"gs, 4 drab fuchsia bags.\nposh olive bags contain 4 posh fuchsia bags, 1 drab brown bag, 4 dotted re"
	"d bags.\nclear brown bags contain 1 striped plum bag.\ndark coral bags contain 1 shiny gold bag, 2 f"
	"aded turquoise bags.\nmirrored violet bags contain 1 dotted gold bag, 3 striped salmon bags, 3 faded"
	" crimson bags.\nmirrored black bags contain 5 dull cyan bags, 3 wavy silver bags, 1 posh fuchsia bag"
	".\nbright blue bags contain 3 shiny coral bags.\nlight blue bags contain 1 striped indigo bag, 4 dar"
	"k aqua bags, 3 mirrored tomato bags, 2 vibrant blue bags.\ndark gray bags contain 2 posh chartreuse "
	"bags, 2 mirrored tan bags.\nwavy silver bags contain no other bags.\ndark crimson bags contain 5 mir"
	"rored blue bags, 4 drab green bags, 5 plaid purple bags, 4 clear beige bags.\nwavy indigo bags conta"
	"in 4 faded lime bags, 4 mirrored green bags, 2 posh tomato bags.\nshiny purple bags contain 1 pale g"
	"old bag, 1 dull tomato bag.\ndotted olive bags contain 1 drab cyan bag, 4 shiny coral bags.\nfaded p"
	"lum bags contain 5 dotted cyan bags.\nstriped orange bags contain 2 dotted purple bags, 2 dotted ind"
	"igo bags.\ndim tomato bags contain 5 mirrored green bags.\nshiny gold bags contain 1 dull white bag,"
	" 4 dark orange bags.\nposh coral bags contain 2 pale olive bags, 5 clear gold bags, 5 posh turquoise"
	" bags, 5 wavy olive bags.\nmuted crimson bags contain 3 dim black bags, 1 vibrant bronze bag, 3 ligh"
	"t black bags.\nmirrored magenta bags contain 5 wavy silver bags, 5 shiny red bags, 5 pale black bags"
	".\ndull white bags contain 5 bright indigo bags, 3 posh tomato bags, 2 clear lime bags, 5 drab lime "
	"bags.\npale tan bags contain 5 wavy purple bags, 5 muted orange bags, 5 dark red bags.\nmuted tomato"
	" bags contain 1 dim maroon bag, 2 dull yellow bags, 3 vibrant bronze bags, 5 dull blue bags.\npale c"
	"yan bags contain 2 wavy violet bags, 1 clear maroon bag, 2 bright orange bags.\nposh white bags cont"
	"ain 4 dim aqua bags, 5 posh chartreuse bags, 4 drab gold bags.\nwavy crimson bags contain 2 posh mar"
	"oon bags, 5 clear cyan bags, 1 shiny maroon bag, 2 plaid bronze bags.\ndrab purple bags contain 1 sh"
	"iny gold bag, 5 dotted bronze bags, 4 drab gray bags.\ndark green bags contain 3 bright chartreuse b"
	"ags, 3 pale green bags, 5 dotted crimson bags, 2 clear plum bags.\ndim cyan bags contain 2 shiny gol"
	"d bags, 3 light silver bags, 2 vibrant blue bags.\npale maroon bags contain 5 mirrored brown bags, 3"
	" vibrant indigo bags.\nvibrant turquoise bags contain 3 muted cyan bags, 3 dull white bags.\ndim oli"
	"ve bags contain 5 drab salmon bags.\nbright salmon bags contain 3 striped turquoise bags, 2 dark sal"
	"mon bags.\nfaded black bags contain 2 striped plum bags, 3 muted indigo bags.\nclear aqua bags conta"
	"in 2 vibrant bronze bags, 1 vibrant indigo bag, 4 mirrored tomato bags.\nmuted turquoise bags contai"
	"n 3 muted cyan bags, 2 light brown bags, 4 light violet bags, 1 posh salmon bag.\nshiny green bags c"
	"ontain 2 posh tomato bags.\nmirrored indigo bags contain 3 clear lavender bags, 3 muted magenta bags"
	", 3 posh yellow bags.\ndim white bags contain 1 clear gold bag.\ndark teal bags contain 4 light teal"
	" bags, 3 mirrored aqua bags, 5 faded teal bags.\nwavy yellow bags contain 2 dull chartreuse bags, 5 "
	"dull yellow bags, 3 vibrant gold bags.\nlight fuchsia bags contain 5 plaid white bags, 2 mirrored ma"
	"genta bags, 5 striped turquoise bags, 5 light bronze bags.\ndotted plum bags contain 1 muted orange "
	"bag.\ndark purple bags contain 3 dark brown bags.\nvibrant yellow bags contain 4 posh chartreuse bag"
	"s, 1 vibrant bronze bag.\nbright gold bags contain 4 dotted tomato bags.\nfaded brown bags contain 1"
	" clear cyan bag, 4 faded purple bags.\ndotted orange bags contain 5 vibrant tan bags.\nlight green b"
	"ags contain 3 muted orange bags, 4 muted gray bags, 3 faded silver bags, 3 shiny blue bags.\ndark si"
	"lver bags contain 5 dark tan bags, 4 light silver bags.\nvibrant teal bags contain 3 shiny bronze ba"
	"gs, 5 mirrored green bags, 3 plaid aqua bags, 1 bright olive bag.\nmirrored plum bags contain 1 dark"
	" crimson bag, 2 striped gray bags, 3 posh white bags.\nstriped red bags contain 1 dotted black bag, "
	"1 mirrored magenta bag, 3 shiny blue bags.\nshiny beige bags contain 5 striped salmon bags, 2 bright"
	" cyan bags, 4 striped crimson bags.\nclear orange bags contain 1 faded chartreuse bag.\nstriped beig"
	"e bags contain 2 plaid green bags, 1 bright turquoise bag, 1 drab chartreuse bag.\nmuted fuchsia bag"
	"s contain 4 dotted violet bags, 1 vibrant silver bag, 1 shiny cyan bag, 1 vibrant yellow bag.\ndim l"
	"avender bags contain 4 muted cyan bags, 1 striped violet bag.\ndull red bags contain 5 posh bronze b"
	"ags, 3 clear turquoise bags, 1 bright green bag, 1 vibrant white bag.\nmirrored blue bags contain 5 "
	"faded olive bags, 5 light aqua bags.\nbright crimson bags contain 1 posh olive bag, 5 faded white ba"
	"gs.\ndrab silver bags contain 1 muted orange bag, 3 dull green bags, 3 dim aqua bags, 2 striped fuch"
	"sia bags.\nclear fuchsia bags contain 4 drab gold bags.\nvibrant olive bags contain 2 light brown ba"
	"gs, 1 vibrant red bag.\ndim salmon bags contain 3 dark red bags, 5 dark lavender bags, 2 dotted turq"
	"uoise bags, 2 light magenta bags.\ndull crimson bags contain 5 vibrant silver bags.\nwavy blue bags "
	"contain 5 faded turquoise bags, 4 clear beige bags, 4 light green bags, 5 dark gray bags.\nmirrored "
	"aqua bags contain 4 plaid bronze bags, 2 light coral bags, 4 faded orange bags, 5 posh tomato bags.\n"
	"dim blue bags contain 1 bright silver bag, 4 bright cyan bags.\nmuted green bags contain 4 dotted to"
	"mato bags.\npale violet bags contain 3 plaid fuchsia bags, 3 light coral bags, 4 dark gold bags.\nvi"
	"brant purple bags contain 3 vibrant white bags, 1 posh beige bag.\nlight tan bags contain 4 pale mar"
	"oon bags, 4 muted fuchsia bags, 3 mirrored aqua bags.\ndotted green bags contain 4 faded green bags,"
	" 2 striped black bags, 4 dull brown bags, 3 faded aqua bags.\nbright bronze bags contain 2 drab bron"
	"ze bags, 2 pale beige bags.\ndull salmon bags contain 1 faded blue bag, 2 wavy silver bags, 3 posh c"
	"hartreuse bags.\npale teal bags contain 2 dotted beige bags.\nvibrant indigo bags contain 3 pale yel"
	"low bags, 4 vibrant bronze bags, 4 bright cyan bags.\nshiny silver bags contain 2 faded brown bags, "
	"2 dotted lime bags, 5 faded chartreuse bags.\nbright red bags contain 1 posh turquoise bag, 4 clear "
	"aqua bags.\nposh teal bags contain 2 pale beige bags.\nclear lime bags contain 4 vibrant blue bags, "
	"2 wavy silver bags, 5 pale yellow bags.\nfaded purple bags contain 4 faded black bags.\nplaid aqua b"
	"ags contain 4 bright cyan bags, 2 pale black bags, 3 dull salmon bags.\ndark violet bags contain 4 m"
	"uted green bags, 2 dotted bronze bags.\ndull aqua bags contain 5 posh aqua bags, 2 clear plum bags, "
	"2 dim maroon bags.\nshiny chartreuse bags contain 4 dim turquoise bags, 2 posh fuchsia bags, 3 dark "
	"blue bags, 4 shiny aqua bags.\npale plum bags contain 4 drab black bags, 4 vibrant purple bags, 1 mu"
	"ted turquoise bag.\nshiny indigo bags contain 2 wavy magenta bags.\npale brown bags contain 3 posh p"
	"urple bags, 5 light aqua bags, 3 striped maroon bags.\nposh tan bags contain 4 striped salmon bags, "
	"4 dark brown bags.\nplaid lime bags contain 3 drab green bags.\nclear olive bags contain 4 dark blac"
	"k bags, 4 drab indigo bags, 3 clear lime bags.\nstriped olive bags contain 3 bright plum bags, 5 dot"
	"ted gray bags.\nplaid turquoise bags contain 4 mirrored magenta bags, 3 clear lime bags, 5 dark turq"
	"uoise bags, 4 dotted olive bags.\ndotted violet bags contain 4 striped fuchsia bags, 4 wavy tomato b"
	"ags, 3 dim white bags, 2 clear gold bags.\nmuted silver bags contain 5 plaid tan bags, 2 dim olive b"
	"ags, 4 dull cyan bags, 5 posh violet bags.\nstriped blue bags contain 1 striped chartreuse bag.\nmut"
	"ed plum bags contain 2 posh tomato bags, 4 faded lime bags, 5 dull bronze bags, 5 wavy lime bags.\nf"
	"aded yellow bags contain 2 dotted tomato bags, 3 muted yellow bags, 1 dim bronze bag.\ndull chartreu"
	"se bags contain 2 striped red bags.\ndotted tan bags contain 4 light aqua bags.\nbright indigo bags "
	"contain 2 posh tomato bags, 5 vibrant indigo bags, 2 posh chartreuse bags, 1 wavy silver bag.\nbrigh"
	"t plum bags contain 3 light green bags, 4 wavy gray bags, 3 mirrored red bags.\nwavy teal bags conta"
	"in 4 vibrant blue bags, 4 posh turquoise bags.\nstriped indigo bags contain 4 shiny gold bags, 3 dim"
	" aqua bags, 5 pale black bags.\nposh brown bags contain 4 muted crimson bags.\ndotted teal bags cont"
	"ain 4 bright beige bags, 3 posh olive bags, 2 dull coral bags.\ndim yellow bags contain 2 shiny gray"
	" bags, 3 faded fuchsia bags, 3 wavy tomato bags, 2 light brown bags.\nfaded magenta bags contain 5 p"
	"ale silver bags.\ndull magenta bags contain 5 dull fuchsia bags, 1 drab green bag, 1 wavy red bag, 1"
	" wavy fuchsia bag.\nfaded salmon bags contain 2 faded gray bags.\ndim bronze bags contain 4 dark gol"
	"d bags, 3 bright orange bags, 2 striped indigo bags.\nfaded tan bags contain 2 striped salmon bags, "
	"5 muted violet bags, 4 dotted violet bags, 4 light green bags.\nposh salmon bags contain 1 dull gree"
	"n bag, 2 bright cyan bags, 1 mirrored bronze bag.\nlight brown bags contain 3 posh chartreuse bags, "
	"5 mirrored bronze bags.\nposh silver bags contain 1 dim yellow bag, 1 clear tan bag.\nmuted brown ba"
	"gs contain 5 dotted maroon bags, 4 shiny yellow bags, 5 dark orange bags.\ndrab coral bags contain 4"
	" faded chartreuse bags, 1 vibrant bronze bag, 5 shiny bronze bags, 3 vibrant tan bags.\nvibrant maro"
	"on bags contain 2 striped yellow bags, 2 muted indigo bags, 3 muted aqua bags.\ndim gold bags contai"
	"n 2 bright violet bags.\nplaid tan bags contain 5 muted gray bags, 5 muted coral bags, 2 wavy green "
	"bags.\ndim coral bags contain 1 clear bronze bag, 2 dark gold bags, 3 drab teal bags.\nvibrant gold "
	"bags contain 3 dark chartreuse bags, 1 posh purple bag, 1 striped white bag, 2 dotted chartreuse bag"
	"s.\nmirrored olive bags contain 4 striped fuchsia bags, 2 wavy indigo bags, 3 drab gold bags.\npale "
	"aqua bags contain 5 faded chartreuse bags, 3 faded crimson bags, 5 dotted orange bags, 3 light brown"
	" bags.\nmirrored cyan bags contain 4 dull blue bags, 4 striped gold bags, 2 plaid lavender bags, 4 l"
	"ight silver bags.\nbright yellow bags contain 4 posh yellow bags, 5 mirrored tan bags, 2 posh tomato"
	" bags, 4 light indigo bags.\nclear cyan bags contain 1 dark gray bag, 4 vibrant indigo bags.\nbright"
	" teal bags contain 3 mirrored tan bags.\nmuted blue bags contain 2 clear white bags, 4 vibrant red b"
	"ags, 2 faded orange bags, 2 clear plum bags.\ndark turquoise bags contain 1 drab violet bag, 5 drab "
	"gold bags, 1 mirrored green bag.\nvibrant bronze bags contain 3 dim aqua bags, 3 light aqua bags, 3 "
	"wavy silver bags, 2 posh tomato bags.\nposh fuchsia bags contain 3 dark brown bags, 5 striped indigo"
	" bags, 1 muted indigo bag, 4 mirrored bronze bags.\nposh blue bags contain 4 clear black bags.\nmirr"
	"ored salmon bags contain 1 dotted gray bag, 3 clear gold bags, 5 dark indigo bags, 2 striped gold ba"
	"gs.\ndark gold bags contain 2 vibrant blue bags, 3 muted indigo bags.\ndark chartreuse bags contain "
	"4 shiny tan bags, 1 wavy lavender bag, 3 vibrant olive bags, 3 light green bags.\ndrab olive bags co"
	"ntain 4 faded salmon bags, 4 drab white bags.\nposh purple bags contain 3 wavy gold bags.\nplaid cor"
	"al bags contain 3 pale bronze bags, 5 mirrored green bags, 2 muted tan bags, 2 wavy silver bags.\nsh"
	"iny magenta bags contain 4 striped green bags, 5 mirrored brown bags.\ndull gray bags contain 5 vibr"
	"ant indigo bags, 3 clear fuchsia bags, 4 dotted teal bags, 4 dim bronze bags.\nclear blue bags conta"
	"in 4 shiny cyan bags, 1 striped fuchsia bag.\nshiny white bags contain 4 faded tan bags, 2 shiny gol"
	"d bags, 1 shiny bronze bag, 1 dim coral bag.\nbright black bags contain 5 shiny gray bags, 3 dull br"
	"onze bags, 4 striped gold bags.\nfaded silver bags contain 3 clear gold bags, 4 dotted cyan bags, 1 "
	"light white bag, 4 dull green bags.\nclear plum bags contain 2 drab silver bags.\ndark orange bags c"
	"ontain 4 dim aqua bags, 4 drab violet bags.\nshiny salmon bags contain 5 faded violet bags, 3 muted "
	"fuchsia bags.\nplaid orange bags contain 5 light beige bags, 1 dull salmon bag.\nposh bronze bags co"
	"ntain 4 faded blue bags, 5 bright orange bags, 3 dark gold bags.\nstriped plum bags contain 2 vibran"
	"t bronze bags.\nvibrant gray bags contain 1 clear magenta bag.\nplaid purple bags contain 1 light aq"
	"ua bag, 5 vibrant tan bags, 4 pale tan bags, 4 wavy bronze bags.\nfaded blue bags contain no other b"
	"ags.\npale turquoise bags contain 1 vibrant gray bag, 3 plaid purple bags, 5 drab coral bags, 5 plai"
	"d indigo bags.\nvibrant tan bags contain 4 pale yellow bags.\nstriped gold bags contain 1 dull salmo"
	"n bag.\nfaded indigo bags contain 4 faded chartreuse bags, 2 wavy silver bags, 1 shiny green bag.\nl"
	"ight plum bags contain 2 faded chartreuse bags, 1 plaid lime bag, 1 posh violet bag, 5 faded plum ba"
	"gs.\ndim indigo bags contain 2 dim black bags, 1 wavy plum bag, 4 dark blue bags.\nmirrored bronze b"
	"ags contain 4 dark gold bags, 4 posh tomato bags, 2 plaid aqua bags.\nposh indigo bags contain 2 dim"
	" maroon bags, 1 dotted gray bag, 4 dark brown bags, 3 wavy indigo bags.\nmirrored silver bags contai"
	"n 3 dull aqua bags, 5 mirrored purple bags.\ndrab magenta bags contain 5 pale beige bags, 4 dotted i"
	"ndigo bags.\ndrab bronze bags contain 1 dotted brown bag, 5 clear beige bags.\nmirrored lavender bag"
	"s contain 4 posh purple bags, 2 mirrored cyan bags, 3 drab gold bags.\ndotted purple bags contain 2 "
	"striped teal bags, 5 clear plum bags, 2 striped lavender bags, 2 dull violet bags.\nlight aqua bags "
	"contain 2 faded blue bags, 4 drab violet bags, 5 dim aqua bags.\ndim green bags contain 5 dark bronz"
	"e bags, 3 light crimson bags, 2 bright yellow bags.\ndotted cyan bags contain 3 light aqua bags.\nmu"
	"ted gold bags contain 5 shiny maroon bags.\nshiny crimson bags contain 5 pale aqua bags, 4 dull salm"
	"on bags, 4 dark turquoise bags.\ndotted beige bags contain 2 drab cyan bags, 5 mirrored bronze bags,"
	" 4 vibrant bronze bags, 5 shiny blue bags.\nmuted chartreuse bags contain 3 plaid beige bags.\nstrip"
	"ed lime bags contain 2 muted orange bags.\ndull violet bags contain 2 dark gold bags, 4 posh maroon "
	"bags, 2 vibrant teal bags, 4 drab teal bags.\nshiny bronze bags contain 5 light tomato bags, 1 dull "
	"blue bag, 4 dark black bags, 1 posh chartreuse bag.\nclear green bags contain 1 light green bag, 5 d"
	"im plum bags.\nwavy black bags contain 3 clear fuchsia bags, 2 striped violet bags, 1 vibrant indigo"
	" bag.\nposh lime bags contain 5 pale cyan bags, 3 clear fuchsia bags, 1 posh white bag, 4 dark turqu"
	"oise bags.\nstriped violet bags contain 5 bright white bags, 5 dull blue bags, 3 light tomato bags, "
	"3 mirrored green bags.\ndotted brown bags contain 5 posh tomato bags.\ndotted red bags contain 4 dim"
	" tomato bags, 1 drab beige bag.\nwavy white bags contain 5 plaid crimson bags, 2 light magenta bags."
	"\nmuted teal bags contain 5 dim crimson bags, 1 dim cyan bag.\nbright lavender bags contain 2 dark l"
	"avender bags, 2 mirrored cyan bags, 1 dim yellow bag, 5 vibrant teal bags.\nclear coral bags contain"
	" 2 drab beige bags, 1 drab yellow bag, 1 dotted tan bag.\nclear gray bags contain 3 plaid lime bags,"
	" 1 dull beige bag, 5 light beige bags.\ndrab tan bags contain 3 dull salmon bags, 3 wavy tomato bags"
	", 2 muted orange bags, 5 clear cyan bags.\nmuted gray bags contain 5 dull cyan bags, 4 clear olive b"
	"ags.\nstriped black bags contain 4 dull plum bags, 3 faded gray bags, 3 faded cyan bags.\nclear viol"
	"et bags contain 4 posh bronze bags, 1 pale gold bag.";
static const unsigned int input_len = 44864;
