static const unsigned char input[] =
	"107\072 18 | 47\n116\072 1 18 | 111 47\n21\072 45 47 | 110 18\n20\072 2 47 | 76 18\n44\072 47 47 | 1"
	"8 107\n2\072 47 18 | 107 47\n113\072 51 47 | 35 18\n80\072 18 22 | 47 44\n110\072 18 18 | 47 107\n1\072"
	" 22 18 | 112 47\n77\072 47 7 | 18 113\n16\072 121 47 | 2 18\n66\072 91 18 | 58 47\n86\072 12 18 | 78"
	" 47\n72\072 18 76 | 47 121\n46\072 47 68 | 18 82\n131\072 66 18 | 75 47\n108\072 84 18 | 24 47\n27\072"
	" 22 47 | 110 18\n53\072 108 18 | 122 47\n90\072 77 47 | 37 18\n6\072 18 29 | 47 52\n10\072 76 18 | 4"
	"4 47\n43\072 47 39 | 18 130\n106\072 18 112 | 47 110\n89\072 97 47 | 51 18\n84\072 112 18\n91\072 74"
	" 47 | 110 18\n114\072 18 47 | 107 18\n105\072 26 18 | 118 47\n18\072 \"b\"\n19\072 2 47 | 22 18\n15\072"
	" 34 47 | 2 18\n111\072 110 47 | 22 18\n94\072 47 95 | 18 57\n34\072 107 107\n60\072 47 114 | 18 121\n"
	"62\072 44 47 | 45 18\n50\072 38 47 | 103 18\n61\072 18 44 | 47 110\n87\072 112 107\n8\072 42 | 42 8\n"
	"11\072 42 31 | 42 11 31\n31\072 18 49 | 47 25\n57\072 18 20 | 47 60\n103\072 18 67 | 47 40\n39\072 1"
	"8 45 | 47 22\n128\072 112 18 | 13 47\n5\072 45 47 | 44 18\n13\072 18 18\n3\072 47 10 | 18 80\n124\072"
	" 22 18\n88\072 18 18 | 47 18\n54\072 32 18 | 129 47\n63\072 81 18 | 86 47\n49\072 18 132 | 47 105\n1"
	"02\072 10 18 | 120 47\n93\072 18 44 | 47 34\n65\072 107 2\n132\072 83 47 | 14 18\n125\072 18 43 | 47"
	" 71\n109\072 47 22 | 18 76\n117\072 18 112 | 47 22\n59\072 47 22 | 18 13\n75\072 18 109 | 47 27\n4\072"
	" 47 90 | 18 69\n48\072 18 65 | 47 115\n24\072 18 2 | 47 44\n42\072 47 50 | 18 4\n96\072 106 47 | 16 "
	"18\n101\072 111 47 | 91 18\n58\072 47 76 | 18 73\n79\072 47 73 | 18 22\n12\072 47 34 | 18 88\n25\072"
	" 33 47 | 55 18\n130\072 18 114 | 47 44\n83\072 126 18 | 102 47\n45\072 47 18\n9\072 41 18 | 62 47\n7"
	"8\072 112 18 | 45 47\n14\072 3 47 | 85 18\n97\072 47 45 | 18 22\n22\072 18 47\n41\072 18 22 | 47 112"
	"\n112\072 18 47 | 18 18\n68\072 21 18 | 19 47\n121\072 47 47 | 18 18\n119\072 22 47\n129\072 47 5 | "
	"18 39\n30\072 73 18 | 2 47\n98\072 34 18 | 45 47\n40\072 18 70 | 47 9\n7\072 64 47 | 79 18\n115\072 "
	"121 47 | 44 18\n32\072 19 47 | 30 18\n73\072 18 47 | 47 18\n35\072 18 76 | 47 45\n95\072 93 18 | 72 "
	"47\n52\072 28 47 | 124 18\n126\072 59 18 | 92 47\n26\072 104 18 | 89 47\n81\072 47 98 | 18 127\n0\072"
	" 8 11\n64\072 112 47\n71\072 47 119 | 18 117\n74\072 47 47\n82\072 47 120 | 18 17\n56\072 74 47 | 88"
	" 18\n123\072 88 47 | 76 18\n33\072 6 18 | 63 47\n104\072 80 18 | 128 47\n99\072 98 18 | 23 47\n38\072"
	" 94 18 | 53 47\n36\072 47 110 | 18 74\n37\072 47 48 | 18 101\n70\072 61 47 | 87 18\n55\072 47 54 | 1"
	"8 131\n23\072 2 47 | 112 18\n122\072 10 47 | 64 18\n120\072 88 18 | 112 47\n28\072 18 112 | 47 73\n5"
	"1\072 47 74 | 18 110\n17\072 47 88 | 18 22\n127\072 18 73 | 47 45\n69\072 125 18 | 46 47\n92\072 2 4"
	"7 | 114 18\n29\072 117 18 | 56 47\n67\072 18 96 | 47 116\n85\072 18 36 | 47 15\n100\072 18 123 | 47 "
	"12\n47\072 \"a\"\n118\072 100 47 | 99 18\n76\072 47 47 | 47 18\n8\072 42 | 42 8\n11\072 42 31 | 42 1"
	"1 31\n\nbbbbbbbbbaaaabbaababbabbaaabbbabbbbaaabb\nbabaabbaabbbbaababbaabbabaababba\nbaabbaaabbabbbba"
	"aabababb\nbbbbababbaabbbabbabaaaaaaabbbbbbabbabbbaabbbbbbbbbaaaaab\nbbbbbabbbbbbaaabbaaaaaba\nbaabba"
	"bbbaabbbabbaabbabbababaaab\nbbabbbbaabbabaaababbbbbbbbbabaab\naaababbaabbaaabbbbbbbabbbaaaabbaabbabb"
	"abaababbaa\naabbbabbaaaaaaabbbabbaba\nbaabaaaabbbababbbbaabbbb\nbbbbabababbbbabbbbbbbbba\nbabbaababb"
	"bbababaabaababbbabbbbbaabaaabb\nbaabbbabaabbabbbaaaaabba\nbaabbabbbbaabbbabbbaaabb\naaaaabbaababaaba"
	"abbabbbbbabbabaabbaaabbb\nbabbaabaaabbbbbbbbbbbabbaabbaaabbaaaaabbabbaabaabaaabbbaaabaaabb\naaabaaab"
	"baaaaabbabaaaaababbabaaababbaabaabbaaaabaaaabaaaaaaabbaaababbbbb\nbaaababbbaabaaaaaaaaaaaabbababaaba"
	"baaaaabaaabaaa\nabaaaaabbbaababababaaaba\nabbaabbabaaabbabaaaaaabaababbabbbbbbabbaabaabbbb\nbaabbaba"
	"aaaabbabbaaaaaabaababaab\nabbaabbabbaabaaaabbaaabbabbaaababaaaaaaa\nabaaaaabbbbaabbabbbbbbaaaaaaabab"
	"bbbbbaaa\naabbaaabaaaaaabababaabab\nbbbabbaaaaabaaaaaabbbbaa\nabbaaababbaaaabbaabaaabbbaaaabbbbbbbaa"
	"aaabbbbabaabaabbab\naaaaaaaaaababbabbbabbaba\nabbaaaaabbbabbbaabbaaabbabbbbaabbabbabbbabaababbbbabaa"
	"ba\nbabaaaaabaabbaaabbaabaaababababa\nbababaabbaaaabbabbbabbbabaabbaaaabbaaababbbbbbaaaaababaa\naaba"
	"abbababbbabaaaaaaaabababaaaababbabaabbaaaaabbbbbbaab\nbaaabbbbaaabbaabaaaaabaaababbaabaaababbabaabab"
	"bb\nabaabbbaaabbabbabaaababbbbabbaaaabaaaabb\nabbaababbaaaaabbbbaaabbb\naabbabbabbaaaaaabbbaaabb\nba"
	"abbbabbabbaababbabbbbabaabbbabbbbabbbaabbabbaababbbbbaabbababbaababaab\nabbaabaabaaabbbbbaaabbababab"
	"babbbaabbabbaaabbaaababbbababbbbbaaa\naabbbaabbbbababbbabaabaa\nbaabbaaaabbbaababaabbabbabbbbbaababa"
	"baaabaabbbbaaababbbb\nabbabababbbbbabbababbbaaaaaaabbbaabababb\nbaaabbabbbbaababbbaaaabb\naabaaaaaaa"
	"aaaabbbabbbabbaaabbbab\nabbaabbababbbbaabaaaabbaababbabbaaabbbbabbbaaabbbbaaaabb\nbaaabbabbbaabaabbb"
	"abbaba\nabbbbbaaabababbbbbbabbbb\naaabbabbbbaabbbabbaaabbb\nbabbbbaaabaaabbaabaaaaabbabbaaab\naaabba"
	"baabbaababaabbbbbbbabaaaba\nbaaaaabbababbbbabbbbabbbababaaaa\nabbaaaabaabbbaabbabbbbab\nbbbaabbaabaa"
	"aaaaababbbbaabbaaaaabbaaabbabbabbbaa\nbaabbbabaabaabbaababbabbbbaaaaaaaabbbaabbbabbbaa\nbabaabbabbbb"
	"aabaabababbbaabaababbbbaabbb\naabbbabbbaaaaaababbaaaaaaabbaaabbabbabbaaabbaaba\naaabababababbbabbbaa"
	"baabaaababbaabbbaabbbbaaaaba\naaabaaababbaababbbbabbab\nbaaabbabbaabaaabaaaababbabbbabba\nabbbabaaaa"
	"bbbaaaabaabbabbbaabbbbaaabaabb\nabbbbabbabbaababbbbbbbaabaaabbbbabaabababbbaaaabaabbaaba\nbaabbababb"
	"babaaaaabbbaab\naaaabbaabbaabbbbaabbaaaabbabbabaabaaababbaabaabababbaabbbabbbaabaabbbabbbabaaabb\nab"
	"aaaaabbabbaaaabbabbbaa\nbaaabbbbababbbaaaababbabbabbaababbabbbabbbbbaaaa\naaaababbabaaaaabbbaabaabba"
	"babbbbaabbaaabbbbaaabbbabbbaaaababbaba\nabbaaabbbbbbaaabaaaaaababbbbbaaa\naaaaabbababbaabaabaaaaaaba"
	"bbbaabaaaabbaa\nbababaabbbbbaaababbaaaaaaabbbbabaaaaabbbaabbbaaa\nbbaabbaaaabaaabbaabbaaaabbabaaaaba"
	"abbbab\naabbaaabbaabaaaaaaaababbbabaabbaaaababbb\nabbbaabaabbaabbbaaaababa\nabbaaabbaabaaaabaababbbb"
	"\nbaabababbbbaaabaaabbabababbbabba\nabaaabbaaaabbabaabbaaabbaaaaaaaaabbbaababaababbaaabaaaaaabbbabaa"
	"\nabbbbbabaabbaaabaaaaaabb\nabbaabbaabbbbaabbbaabaababbbbbaaababbbbb\naaabbababaaabbabbbaaabbb\nbaaa"
	"babaababaabbbbbaabaa\nbbbaababbbaaabbaaaaabbabbabbbbab\nbbaabaaaaaababbabbaaaaab\naaabaaabbabbabbabb"
	"aaaaba\nbabbabababbbbabbaabbbaba\nababaabbbaabbaababbaabababbbabbbabbbbaabbababaaababbbabbbbbabbbb\n"
	"abbbbabbaababbababbbbbaaabababbbaabaaababbbaaabb\nbabaabbbababaabaabaaabbbbaabbbaa\nbbbbabbbbbababaa"
	"bbbbaaabbaabababbbbbabaabaaaaaaa\naabbabaaaaabaaabaaaaabab\nabababaaabbabaaabbaaabbababbbbaaaaaababb"
	"babbbaaa\nabbaaaaabbabbbbaaabaabbabbaabaababbaaabaaababaaa\naabbbabbababaabbababaabbaaabbbab\nbaaaaa"
	"bbbbbbbbaaabbbbbabaabaababaaaabaab\nabaaaaaaaaabbababbabababaabbbabbbbaabbababbbaaab\nbaabaaaaabbaaa"
	"abbbbabaaabbababababbbbbba\nbaabaaababababaaaabbabaaaabaabababaaaabb\nbbaaabbaaaabaaababbbbabbaababa"
	"aa\nbabaabbaabbbbaabbbaaabbabbaabbbbbabbbaaa\nbbaaaaaaabbaaaaaababbaaaababbbabbbbaaaabbaabababababba"
	"bbbbbbaabbaaababbbbbbbbbab\naabaababbabbaaaaabaaaaabbababbaa\naaabbaabaabaabaabbbaababaabaabaabbaaba"
	"abbaaabbaa\nabaaabbabbbabbaabbbbbabbabaababbababbaaa\nbbabaaaaaababababbababba\naaabbabbbabbbbbbabba"
	"abbbbbbaababbaabaaabababbbbbabbabbaa\naabbbbabbabbabaabababbaa\naabaaabaaaabaaaabbabbbbaaaabbbbb\naa"
	"aabbabbbabbbbbbaaababaaaaabbabaaaaabab\nbaabbbabaaabbabbbbababba\nbbbabbbaabbaabaabbabababbbbababbab"
	"aaabbababbabbbabbbaaaabbaaababbaababaa\nabbaabbbbaaabbabbaaaaaaa\naabaaabaaaaaaaaaaaaaaabb\nbabbaaaa"
	"bbabaaaaaaaaabbaabbbbaabbbabbbbbbbbaaaaa\naabbaabbbaaaaabbabbbbbba\nbaaaaabbaaabaaaaabaabbaa\nbbaaba"
	"abbaabbbabbabbbaabbbabbbaababaabab\naaabbabababaabbabaaababaaaabbabbbbabbaabbabbbbba\nbbaaabbabaaaba"
	"bbabaaaaaabaabbbaa\nbbbbbabbabbbbbabbbbababa\nabaabbbabaabbabababaabaa\nbabbabaaaaaababbbaaaaabbabab"
	"babbbbbbbabbbbbbabaa\naaaababbabbbbbaabbbbaaabbaaabbbbaabbbbbababbaabababbbaaa\nbabaaaaaabbbabbbaaba"
	"abbabaaabbbbbabababbbaabbbaabbaabbaa\nababbaabbbbbbabbbabaaabbabaabaabbababbbbabbbbaab\nabaaaaaaaaaa"
	"aabaabbbbaabbababbbbbaaabbaa\nbbbaabbabbbabbaaaaabbabbbaaaabbaaabaabbb\naaaaaaabaaabaaabaabbaaabbbab"
	"bbabaaaabaaababbbaaa\naabbbbababbaaababababaabaababbba\nbbabbbbbbabaabbbbabbababaaaaabaabbaaabaabbba"
	"bbabababbaaa\nbabaabbaabbabbabbabbabaaabbabaab\nbbbabbbaabbaaabbaabaaabaaababbaa\nabbbabbbababababba"
	"aabbab\nabbaaaaababbababaaaaaabaaabaaabb\naaaaaabaabbaaabaaabaabbabbabbaab\naabababaaabaaababaabaabb"
	"aababaabbaabaaba\nbbababaabaabababaabaaaabbaaabaab\naabbbbabbaaabababbabaabb\nbbbbbbaaaabbbbabbabaaa"
	"ababbbbbba\nababbbbabaabaaaaababbbbaabbaaaabbbabbaaa\nabbaaabbaabbaabbaaaababbbaabaabbaabbbbbabababa"
	"aabbaaababbbabaaab\naaaaaaabbaaaaabbabaabaabbbbbbbabbbbbaaaabbbabbbb\nbabbabbaaaaaaaaabbbaaabb\naaab"
	"aaaaaaaaaabaabbabaaabaaababbbbbabaaaabbbaaba\naabbaaabbaabbabbbbabbaaa\naabbbaabaabbbbbaabbaaababbaa"
	"bbbabbbabbbb\nbbbabbbabbababababababbbabbababb\naaaaaaabaabbabaaababbbbb\nbbabababbbbabbaabaaabbabab"
	"baaaaabbaaabaa\nbbabbbbaaabbaabbabaabbaa\naaabbaabaabaabbaabbaababaabbbaabaabaabbababbabababaaabbbbb"
	"abaababaaaababbbbbbbbabababbba\nabababaaabbaabbabbbbaaaa\nabaabbbaaabbbabaabababbbabaaaaabbaaaaabaaa"
	"bbabbbbaaaaaabbabbabab\nbaabababaabbaabbbbababba\nabbaaabbabbaabaabbabbaab\nbaabbaababaabaababaaabab"
	"\nabaabaaaaaababbabbabbaba\nbaaabbbbbbbbbbababaabbab\nbabaaabbaabaabbaabbabababababbba\naaababbaaaba"
	"abaabbbabbbababbbaabaabbbaaa\naabbaaaaababbbbaababbaaa\nbabaaaabbbabbbbababbbabb\nbbbaabbabbbaabbabb"
	"abbbaa\nbabaaaaaabbaabbabbaabaabbbbbbabbbbaaabbabababaaaaaabbbbb\nbabbaaaabbbbababbaabbbabbaaabaabba"
	"abbbba\nbbbbbbaabaaababaababbaabababbbab\nabbabbbbaabbbbaaabbbaabbbbabbabb\nbbbabaaaaabbaaabbabababb"
	"\nabbaabababbbbaababbabbabbabbaaaaaaaaabaaaaaabaab\naabbabaabbababaaaaabbababbaabaaabaaaaaaa\nbbbbaa"
	"bbbbbababaabbbabaaaabababb\nbaabbabbaabaaabaaabaaabababaabab\nbaabaaaaaabbaaabbbabababbabbbbbbbbbbaa"
	"aa\naaaaaaababaabbbabbaabbbaaaaabaababbbaaababbbaabaabbbbbbbababbababaabbaab\nabbabbbbbbbbbabbababaa"
	"aa\nbabbbaabaabbbbabbaabbaabbbbabbaabbabbaab\nababaabbbbaabaabaaabbabbbaaaaaaa\nbaaaaaabaabbaaababbb"
	"babbabaaababbbaaaaba\nbbbbabbaaabbbaabbaaaabab\nababbbaaabbabbabbbbabbab\nabababaaaaabbabbbbabaaba\n"
	"aaaaabbabbabbbababbbabba\naabbbbbabbabababaabbaaabaaaaabbbbbbaaaab\nbbbabaaabbbabbbaaaabbababbbbbaba"
	"\naaabaaababbbaababaabbbaa\naaaababbbbbbbbabaabbaabbabbbabbbbababaaabbbaabbbbabbbbab\naabaabbabaabab"
	"abbabaabbaaaaaabab\nabbaabababaabaaababbbbaaaabbaaba\nbbabababbaabaabbababbaaa\nbabaaaabbaabababbbba"
	"abbaaaabaaabbababbaaaaaabbaabbbaaaaa\nbbbabbbababbbbbbbaaaabaa\nbbbbabbaababbbaabbabbbbabbabaaaaaaba"
	"ababababaababbaababbbbbbaaaa\nbaabbbbaaaabbbabababbaba\naabbbbabbbbbababbbababbbababbaaaabbbbaaa\naa"
	"bbaaabbbabababbbbabbbabaabbaaababbaaababababba\nbaabaabbbaabaaababbbbaabbaaaaababababbbabaaabbbbbaab"
	"abababaaaaaa\nbababbbbaabaaaababbaaabbbabaabab\nbabaabbbaaaabbbaaaaabbbbabbbaaaabbabbaba\nabaaaaabbb"
	"babbaabbbbbbabaaabaabb\nababaababbaabaabababbaba\nbaabaaaabaabbabbbbabaaaababbaaab\naaaabbbabbbbbbab"
	"bbabbabb\nbbbbbbabbabbaaaaabaaabbabaaababbaabbbaaa\nbbbbbabbbbbaababbabababb\naaabbaababababaababaaa"
	"bbabaaabbb\nbaabaabbaaaaabbabaabaaaaabaaabab\nbbbbbbababbbbaababbabbabbbbaabaa\nabaabbabbabaababbbbb"
	"bbbabbbbbbaaabbbaabaabbbbbbbbbbbaaab\nabaabababaabbabbbbbbabbabaaabaab\nbbabbbababbaabbaababbbbaabba"
	"abbbbbaabaabbabaababbbababbbbaababaa\nabbaaaaaaaaabbbaabbabaaaabbaaaaaababbabaaaaabaabaabababb\naaaa"
	"abbaaaabbbbaaaabbbbaaaababbababbbaabbaababbababaaabaaabaaabbbbaaaaab\naabaabbaaabaaabaaabababb\naaab"
	"babbabaaaaabbbbbababaaaabaaa\nbaababababbbbabbabbabaaaaabaaabbaaababbb\nababbbbaabbaabbaabbbbaaa\naa"
	"aabbabbbabaaaaaabaabbb\nbbbbabbaaaaaabbabbbababa\naaaaaabbbabaaababaaabbaaabaabbbabaaababbbbabaabaaa"
	"babaabaaaaaaaaabbbaaaababaabaa\nbaabbbababbbbbaabaabaaaaaaabaabb\nabbabbabbbbbabbbaaaaabbabaaabbaa\n"
	"baabaaababaabaabbaabbabbaaaaaaababbabaaaaababbba\nbaaabbabaaaaabaaabbabbbaaababbba\naabbaaababaabaaa"
	"babbaabaaababbabbabbbbabbbaaaabb\nbaabbaaabaabbaababbbbaba\naaaaabaabbaaabbaaabaaaabbaabbaaaaabaaabb"
	"\nbbaababaabaaabbababababb\nbbabbabbbbaaaaaaaaaabaabbbaaabaabbabbabbbbbbabbbabbbaaaabaababbbbabbbbab"
	"ababbaab\naaabbbbabaabaaaaaaabbbab\nbaabbbabbbbabbaaabaaabab\nbbaaabbabaabababaabbabbabbaaabaa\nabab"
	"bbaaababaabbbabaaaabbababbbbbaaaaaba\nbaabbaaaabaababaaabababb\naababbabbbababababbbbbaabaabbaaaaaaa"
	"baaabbaaaaba\naaaaaaabbaabaaaaababababbabbaaabaaabaaba\nabbaabbbaabbbabbaaabbaaa\nbaabbaabbbbababbba"
	"aaaabbbbabbabb\naaaaabbababbaaaaabaaabbaabaabbbabaababaa\naabbabbbbbbbabbbbbbbbbba\nabababbbaaaaaaab"
	"aabbabbaabbbbaaa\nabababbbaabaaababbaababaabbabbaa\nbaabbaabaaaaaaaaaaabaaba\nababbbaabbbbababbbaaaa"
	"ab\nbaaabbabaaabaaabaaaabbbbbaaaaaba\nbbaaabbabbabaaaabbaaaaaaababaabbbabaaaba\nabaabbbaabaaabaaaabb"
	"bbbbbaaabaabaababbba\nbbbbabaabbbbbaababaaaaabaaabbabbbabababbbaabbaaa\nabaabaabaaaaabaababaabbbbbaa"
	"baaaaaababbb\naabbbbbaaabbbbabaabaaababbbbbbabbbbaabbbbaabbbaa\nabaabbbaabaaaaaaaaaabaaa\nbaabbbabab"
	"bbaababbabaaba\nbabbbaaaaabbbababbababbabbababab\nbaaabbababbbabbbabbbbbba\nabbaaaaaabaabaabaaabbbba"
	"abbababbababbaaa\nabbaaaabbaaabbababbaababaaaababbbabbaabb\nbaabaaabaaabaaabbaabababbaabaaba\nababbb"
	"baabbaaabbbbaababaaaaabbbbabbababb\nbaabbabbbbabbbbabaabbababbbbababbaaaaaababababba\nabaabaaaabbaaa"
	"ababbaaaabababbbaaababbabaabaabababbbbbaab\nabbbbbabbaaaaaabbabaaaaabaaabbbbbaabababaaababaaabbbabab"
	"\nbaabaaabbabbabababbaaabbbabbabbabbbbbabbbabbbaaabaaaabab\nbabbabaaaaaabbbbabaaaaabaabbbabbabbaaaaa"
	"aababbba\nbabbbabaabbbaaaababaabaa\naaabbabbbabbabaaabbbbabbabbababbabbbabba\nabbaaaabaaabaaabbaabba"
	"baaaababbabaaabbbbbababbaaabbabaab\naabbabaabaaaaabbaabbbaabbabaabab\nbaaaaabbbbaaaaaaabbbbbabbbbbbb"
	"bbaababbbbbbbaabaa\nbbababaaabbaabaabbabababbabaabbbabbaaaaaabbbabbb\naaaabbabbbaabaabaaaaaaaaabbbbb"
	"aaaaabbbababbbaaaa\nabbabbbbbbbbabababaabbab\nbabaabbabbbbabbabaaabbbbbbababbaaaabbbabbabaaabaabbaba"
	"ab\nbbababaaaabbbabbbbababbb\nbaabbbababbaabaabbbbababbababbbbabbbabab\nbaabaaaabbbbbbababbabbaa\nba"
	"baaaaaaabbbaabbbbbbbaabaabaaabaaaaabbbabaaabbb\naaababbaaaaabbbbbbabbbba\naabbbaabbbabaaaaaabababaab"
	"bbabbbbbaaabaabbbaaaba\nabbbabbbbabaaabbbbbbababababbbbb\nabbbbaabaaaabbbaaaabbbbaaaaaabab\nababbbba"
	"aabaaabaababaaab\naaaaaaabbbbaababbaabababaabababaabbbbabb\naabaaaabbaabaaabbaaaaaabbababbbaababaaaa"
	"\naabbabbabaaaaabbaaabbbab\nbbbbbabbbbbbbbabbbabbaba\naabaababaaaabbabbbbaabbaabaaabaabbabababbbaabb"
	"bbbaaaabaa\nbabbabbabbbaababaabbbbbbabbaaabaabbabbbaabbbbbbb\naabbaaabaababbababaaabab\nabaaabaaaaba"
	"bbabbbbbbbabbbaaaaaaabbabbaaaaabbbbb\nbabbbbbbbbaabaaabbbbbaba\naababbaaaaabababbababbbaabbbabaa\nab"
	"bbbbaaabbbbaabaaaabbbbababbbabbbaabbaa\naabbabbaaabaaabaaaaabbabaabbaabbabbbbbabbaabbbba\nbaabbbabba"
	"bbaababbbbabbb\naaaaaaabaabaaaaabbbbbbbbaaabbabbbabaabababababbb\nbbabbbabbabaaaabbaabbbabaaaabbbaba"
	"abbabbbbabbabbabbbaabbbaabaabaaababaaa\nbbaabaabaabbaaaaabaabaaaaabaabbbbababbaa\nbbbababbabaaaaabbb"
	"babbab\nabbbabbbaabbbaabbbbbabbababaaabbabbbbbaabbaabbbbabbababbabbbbbbb\nbabbabbaaababbabbbbabbbaaa"
	"abaaababbaabaaabababab\nbbabaaaabbbabbbaababbabbaababbaa\nabbbbabbabbaaaaaaaababaa\nbbbababbabbaaabb"
	"aabbabbbbbbabbbbaaaabbaa\nabbabbbbbbbaababbaabaabbbbabababbaaaaaaabbbbbababbabaabb\naaaaaababaaabbaa"
	"abaaaabb\nbabbababbabbbaaababbbabbbbbabaab\naaabaaabbabaabbbbababaabaabbbbbaaabababb\naabbbbbaabbbba"
	"bbbbbbababaaaaabbaabbabbabbaaabbbbbbabbabb\nabbabaaababaabbaaabbaaabbaaaababbbbbbbba\nbbbbbbabababab"
	"abbbabbbabbaaaaabbabaaaabaabaaaababababbaa\nabbaabaaaabbabbbabaababaababaabbbbbbbaba\nabbabbbbbabbaa"
	"babbbaabaa\nabbaababbababaabbbaaabbaababbbaaabaaabaabbaaabbb\nbababaabaaaababbbbaaaaaaaaaaabab\nbbbb"
	"abbbbaabbabababbabbb\nabbaaaabaaaaaabaabaaabaaabbbbaaabbabaaba\nbababbbbaaaaaababaabbabbbbaabbab\nab"
	"baaabbababaabaabaabbab\naabaaaabaabbabbabbbababa\naaaaabbabbbbbbaaaaabbabaaaaaaaaaabbbbabbaabbabbabb"
	"abbbaaaaabaabb\nbbbbbaaaabababbababbbaabbabbbbaaaabaabaabaabaaababbaabababbabbbb\nabaabaabaabbbbbbaa"
	"aaabab\naabbabaaababababbbbaabbaabbbbbaabbabbaabaabaaabbbaabbbaa\nabaaaaaaabbaababbbbbbabbbbaabbab\n"
	"babbabaabaaabbbbabbabbaa\naabaaaabababaabaaabbaabbabbbabababbbbbbb\naabbaaaaaaabaaaaabbbbabbbaabbbab"
	"abbaaababbaaababbbaabbbb\naaabbbbabbbbbbbbbbaaabab\naabbbabbbaabaabbaaaaaababbabbbbbbbbaabbb\nbbbaba"
	"bbbababaabaabababb\naabaabaaaaaabbabbaabbaabaaababab\nbabbbaababaaabbaabbaaabbbbbababa\nbaabbaabbbaa"
	"aaaaaaaabbabbabbbaabbabaaabbbbaabbbbbbbaabaaaabaaabbabbabbaa\nabbaababbabaaaaababbbaba\nbbabababaaaa"
	"abaababaaaba\naaaaaababaaaaabbaabbaaabaaaaababababbaba\nbabbbbbbaabbaaaabbbbaabb\nababaabbbbaabbbaab"
	"abbbbb\nbbbabbbaaaabbaabbabbbbaa\naabababaabbaaabbabaaaaba\nbaabaaabaabbabbabbbbbaaa\nbbbbbbbbbbbabb"
	"aabbabbbbabaabbaab\nbabbaabaaabaabaaabaabbbabbabbbaa\nababbbbaaaaaabbaabbaaaabbbaababaabbabbabbbbabb"
	"abaaaaababbaaabaab\naaaabbabbaaabbabababababbaababaa\naaabaaabbabbaaaaaaabaaaabbbbbbbaaaabaabababbba"
	"bbabaaaababbbbabaa\nbabaaaaaabbaabbbbbababaababababb\nbbabbbabbbaabaaaabaaabbabbbbbbba\nabaabaaaaaba"
	"abaaababaabaababbabbbbababbb\nbbaabababbbaababaaabbbbaabaaaaaaabaaabbb\naabaabbaabbbbbaabaaaaaabbaab"
	"bababbaaabbaaabbabab\nbaabaabbaaaaaaabbaaaabab\nbaaabbababbabbbbaabbabab\naabbbbbbbaabbababaabababba"
	"bababbababbaaa\nbbabbbbbbaabbabbabaaaaaabbbbaabb\naabbaaaaaabbaaaaaababbbb\nbbbbabbababbabaaababbbba"
	"abaaaaba\nbbbbbbaaababaabaabbbbaababbbbbabbababbaa\naaaabbbaaababababbbaaabaabaaabbbbabaaaabaabbbaaa"
	"\nbbabbbabbbbbbbbbababaabaabbbabaabbaababb\naababababbabaaaaababaaaa\nbabbaabbbaaaababbbaabaaababbab"
	"aaaabaabaaabbaabbabbabbbbbabbbbbab\naaabbabbaaaaabbaaabbbaabaaabaabb\nabbbaababbbababbaabbbbbbababbb"
	"ab\nbbbabaabbaaaaaabbbbbbaababbaaabaabbabbbbaaaabbaa\naaabaaabababbaabababaaab\nbbbbaabaaabbbaabaaba"
	"bbabaabaaaabaaaabbaaaabaaabb\naaaaaaaababaaaaababbbaabaaaaabbababbbbba\nabbababbbbbaaaababbaaababaaa"
	"baababbabaaabbbbbabaababbabbaaabbabaabaabaab\naaabaaaabbabaaaaababaabaabbaaaaaaababbabbababaaa\nbaab"
	"babbabababababbabbbbbabbabbb\nabaaabbaabbbaababbbbaaabbbbbbabbaabaababbbbaaaba\nababbaabaabbabbababa"
	"aaabbaaaabbabbaabaababbbaabbbabbbbabbbbbaabb\nbaabbbabaabaabbaabbbbaaa\nabababaaaaabaaaabbbbbabbbbaa"
	"babb\nababababbaaabbabababaabbabbaabbbbaaabbababbbbbbb\nabaaabbabbaabbbabbaabababbaaabbb\nbabbabaaba"
	"aababababbbbaabaaaaaabababbbaabaabaaba\nbabaaaaaababaabbabaabaabababaabbbbbbabbbaabbaababaababbaaaba"
	"bbbbbbbababa\nbaabaabbaabaaabaaabbaabbabbabbabbbaaaaaaabbbabab\nbbbaabbababbaaaabbaaabbb\naabaabaabb"
	"bbaaababbabaaaababbabbbbbabbbaabaaabbbbbaaabbbaababaab\naaababbbbaababbbbabbaabbabbabaababaababb\nbb"
	"ababaabbbbabbaaabbabbbababababaabbaaabababaaaa\nbababaababbaaabbaaaabbaa\nabbbaabaaabaabbbaabbbababb"
	"bbabbaabaabaaaaabbbabaaaaaabbb\naabaabbabbabbbbbbbaaaaab\nbbbabbabbbbaabbbabbbabab\nbbaaabbaabaaaaaa"
	"bbaaabbb\naaaaabaabbabaaaababbbabb\naaaaaaaaabbabbbbbbabbbbbaababbaa\nbbbbbbabbbbbabbbabaaabab\nabaa"
	"bbbaabaababaaaaaaaababaaaababbbbaaaa\nbabbbaabbabaaabbbaabbaabbbbabaaaaaabaaaabbbbababbbaabbbbbbbbba"
	"ab\naabbbaabaaaabbbbaaababbabababaabbbbbbbbbbbbababbbbbbaaaaabaaabbbaababaaabbaaaaabbbbaabaa\naaaaba"
	"bbaabbabaaabbabbbaaabbaabbbbabbbbaabbabbaa\nbbaabbaabbbaaaaaaabaaabb\nbabaabbbababaabaabaaaaaaababba"
	"bbababaabbabbbbaba\naaabbabababaaaaabbabaaaaaaaaaaabbbbbaabaaaabbbabbbbbbaab\naaaaaaaaababbaabaababb"
	"aa\nbbabaaaabbaaaaaaaabbbbbbaabaaaaa\nabbabaaaabababaabaabababbaaabaab\nabababbbaababbabbbbbbbbbabbb"
	"babbaababbabbbaabbabbbabbbaabababbab\nbabbbbaaabaabbbaaaabbaaa\nbbbbbbaabbaabaaaabbaaabbbbbabbbbbbba"
	"baab\nbabbaabaabbabbabbaababaa\nabbaabbabaabbaaaabaaaabb\nbabaaaabbabbbbbbaaaabbaabbbabbababbbbaba";
static const unsigned int input_len = 18067;
