static const unsigned char input[] =
	"cqvc vmkt sbvbzcg jjfhf mzjnsm xhnl zlkvkzt ssxljz vshd ptpqnl bzrtth vtffks bnl ntrqq cdhlqp vmks n"
	"pgxl pvzhm vnbrhb ksm gvqdr mml fjbbj gzfm bllk rkgjkvl xmhsbd nhx clbzn vsssd kcrh ttqqvb pnlkl gdb"
	"s fpbqsb jkxsgpk lqttkm lgn rrjb vfktc gcxjz hzhzkn dlcgqg lsnrh sxjxjx rxvzb rvnfcrr rlmv tthhp bqv"
	"r mnlcj pmlqgp kfxr rsbph chbtp gzhzhrc jsqpt bmqh ljxsf rqjdcb fhcmcth fsbn jsjz flhn rtxkp qlrjf d"
	"nprvn ntft lcnxpz npkvt stpzhrp krsdgrm bbqs (contains fish, soy, nuts)\nvshd psqkpr bqprv rvpgl frg"
	"md xnsxv lhfj kfxr cqvc pkvx ncxd zpkl ssxljz vfktc vnbrhb vfrrd dcqqd vcngs rzzt xhghxjg ntft jdmvk"
	" xdp fhcmcth gvqdr xzhxj vtdf rqjdcb sshkphb lkr clbzn bvb bbqs kkbbb pnlkl lmnbtpn ljjl xmhsbd fpd "
	"jsjz rtxkp zlkvkzt pvzhm tdtfnv ntpnb bjslhf qjzq nhx kvzhn xtd jkxsgpk sbvbzcg rrjb hdgrmv zkhfkg v"
	"tffks jxrs (contains nuts)\nxlkf ljjl mbsc pvzhm zlkvkzt gbhqd lmnbtpn mnlcj sbvbzcg psqkpr xjkpm gz"
	"hzhrc cqvc lfxzl lkr sndbnc xzhxj vtffks sshkphb fsbn krsdgrm rkgjkvl lqxt vqgcbr ptpqnl vfrrd jfmvt"
	"dd dlcgqg xmhsbd fchcj ntft qjzq chbtp jsqpt jzjc fxhts rlmv tthhp mftbj jdvxf jsjz qrt zkhfkg ggbpl"
	"n svqkg nhx bbkq stttxbm kfxr rtzcq phgcp vtdf vfcrdm (contains wheat)\ngdnkc jfmvtdd vqjl mbcx jdrv"
	"f ntrqq xmhsbd npgxl vmkt jjrm nhx lcnxpz cqvc vtffks psqkpr kfxr fsbn fchcj bqtdv tthhp mml qxqngjh"
	" ntpnb xnsxv kpjll sshkphb sndbnc tmxm pvzhm cghj lhfj lch kqbkb mmnx bjslhf xzhxj krsdgrm cdhlqp bb"
	"kq rvpgl trls gsq jvv pmlqgp lkr srmtb bllk lfxzl cbxrs tdtfnv qlrjf rrjb bzrtth bqprv xxrzn tbjh jk"
	"xsgpk kcrh gzfm gdvfsd vk xdp fjbbj fxhts ncqr rzzt ptpqnl jzjc mqb rtxkp chbtp bqvr (contains wheat"
	", soy)\nfsbn zmp mbcx ptpqnl hchrm ttqqvb kqbkb lrgd mmnx zpkl bzrtth dmssm lkr bqtdv mnlcj gfvfs vs"
	"ssd sbvbzcg bldts bbkq vjmrl jdvxf jzjc dnprvn fjbbj vnbrhb qbmg rhzjdcjz gdbs xtd lkck dvnbt ggbpln"
	" bvb kfxr cdhlqp xzhxj hzhzkn stttxbm jdmvk lfxzl clbzn srbhb chbtp gzfm rvnfcrr ksm krsdgrm rtzcq j"
	"xrs fxg vfcrdm rrjb jdrvf xmhsbd lqttkm gdvkh vfktc vdqtnr ntft zlkvkzt jsqpt tmxm lhfj phgcp frgmd "
	"plgsn vtffks qxqngjh stpzhrp mftbj vmkt bqprv sjft rnqh fhcmcth sshkphb rtxkp xnhbrx dcqqd nhx vtdf "
	"dhtbh rzzt svqkg lmnbtpn lch cqfld pkvx (contains peanuts, nuts, sesame)\ntthhp sjft zctbc cbxrs jzj"
	"c hzhzkn xxrzn xzhxj qxqngjh flhn rqjdcb xtd ljxsf bqvr ncqr pvzhm jvv lkr ttqqvb jdmvk xmhsbd vmks "
	"xlkf mzjnsm qdt bbkq fhcmcth lrgd dmssm phgcp ntft cqvc jcr cdhlqp lgn sbvbzcg kcrh ptpqnl xkmfx dsp"
	"hl qnqg lfxzl vsssd ggbpln cqfld chbtp vtffks lmnbtpn qrt rsbph kqbkb vnbrhb qlrjf bkkhrl fchcj plgs"
	"n jfmvtdd rkgjkvl gbhqd rrjb rtzcq bvb vjmrl jsqpt clbzn xghfgf rdqs fnngtqh npkvt vmkt jdvxf kfxr d"
	"lcgqg tmxm sxjxjx vk fpd bldts fpbqsb mqb zkhfkg svqkg jjrm vqgcbr lbnsscn kvzhn mmnx (contains soy,"
	" shellfish, eggs)\nvnbrhb ckknl trls nhx chbtp lkr vfktc jxrs kpjll vsssd qzckbb plgsn gfvfs bqprv l"
	"gn hzhzkn pmlqgp sjft pnlkl mml ntft frgmd bkkhrl hchrm qjzq dsjxr flhn xlkf zlkvkzt cdhlqp rtzcq lk"
	"ck xmhsbd ttqqvb vtdf phgcp cqvc bjslhf vdqtnr kfxr dcqqd dsphl lmnbtpn vmks xjkpm jdvxf gzfm xtd lb"
	"nsscn vjmrl tthhp hdzcch jsjz lch jjfhf fpbqsb gdvkh nmnfx xzhxj njdq ptpqnl jkxsgpk zctbc sxjxjx (c"
	"ontains nuts, peanuts, shellfish)\nrxvzb gdnkc mzjnsm lqxt jfmvtdd bvb bkkhrl tbjh vqjl vqgcbr xlkf "
	"dmrvf dlcgqg qbmg gdvfsd ntft jsjz mbcx fjbbj qrt krsdgrm kqbkb xhghxjg vnbrhb qdt xmhsbd ljxsf qlrj"
	"f dcqqd jsqpt vfrrd pkvx clbzn jzjc fpd xtd qzckbb gfvfs njdq lkr gsq xdp bldts gzfm ncqr rlmv xxrzn"
	" fnngtqh qnqg xzhxj vmks chbtp vshd npgxl stttxbm jvv mqb fchcj lch kfxr mmnx hzhzkn kvzhn kcrh rzzt"
	" fxhts phgcp bllk jlpjdb rdqs bzrtth nhx dnprvn svqkg gzhzhrc jdmvk npkvt kpjll rrjb (contains eggs,"
	" shellfish)\ntthhp qxqngjh rrjb fsbn jdvxf fjbbj zkhfkg zmp zctbc vfcrdm mftbj zbm gfvfs plgsn rtzcq"
	" rkgjkvl vqjl stttxbm vsssd ggbpln njdq xmhsbd zpkl rtxkp vmjjv mbsc nhx xzhxj ntrqq ssxljz vmkt qrt"
	" gdnkc zlkvkzt lkr cdqt cqvc pvzhm kfxr rlmv rhzjdcjz rvpgl vfktc dcqqd bjslhf chbtp lrgd rqjdcb gdb"
	"s fhcmcth vcngs ncxd (contains wheat, shellfish, peanuts)\nqdt gdnkc vfrrd xghfgf hzhzkn chbtp lmnbt"
	"pn jzjc xzhxj mqb xlkf kpjll bjslhf fpd gdvfsd plgsn ksm kqbkb lhfj xmhsbd lch xdp cqvc sjft vtffks "
	"vfcrdm vqjl stpzhrp lkr kfxr mbcx mbsc xnhbrx hdzcch zbm rrjb lqxt rvpgl ntft jxrs krsdgrm svqkg lcn"
	"xpz (contains wheat, shellfish, soy)\nvqjl chbtp gdvfsd cdqt dlcgqg xmhsbd bkkhrl dcqqd tbjh zpkl sv"
	"qkg gbhqd xnhbrx cbxrs vcngs xxrzn xzhxj mbcx bbkq vmks fxg gcxjz zlkvkzt zmp fchcj pmlqgp lqxt flhn"
	" ncxd nhx jjrm xkmfx jkxsgpk gdbs kcrh bldts ntft rrjb rdqs ntrqq cqvc qrt kqbkb (contains shellfish"
	", wheat)\nzpkl vfrrd phgcp vdqtnr vbrnf rqjdcb vnbrhb qnqg rrjb cghj rtzcq xzhxj ssxljz xnhbrx xmhsb"
	"d mftbj jkxsgpk vcngs nhx bqprv bbkq rsbph stttxbm dcqqd chbtp vtdf lhfj sxjxjx fpbqsb lgn rdqs frgm"
	"d cdqt tbjh xhnl dmssm jxrs lbnsscn ntpnb vshd hchrm fjbbj bmqh tmxm vk jzjc jdrvf vqjl qdsp cqvc nt"
	"ft (contains sesame, fish)\nhdzcch lkr gdvfsd tbjh mnlcj dlcgqg rnqh xzhxj cqvc bjslhf srbhb jxrs vt"
	"ffks xhnl qbmg kkbbb bzrtth xmhsbd kqbkb qbdjjt fxhts bbkq dcqqd rqjdcb sjft rvpgl vjmrl mbsc dvnbt "
	"stttxbm gvqdr ntft srmtb gdbs sndbnc jfmvtdd bnl rlmv fxg fpbqsb lbnsscn ljjl tthhp cdhlqp rzzt xtd "
	"jdrvf fpd ntpnb xlkf vmks jdmvk rrjb lqxt bqprv gfvfs fklqd ttqqvb chbtp njdq kfxr jsjz svqkg jvv mf"
	"tbj npgxl zkhfkg gzhzhrc (contains sesame, eggs)\npmlqgp xnsxv bnl jfmvtdd xxrzn xhghxjg jjrm mftbj "
	"xzhxj pvzhm vtffks cdqt cdhlqp npgxl rlmv trls svqkg hzhzkn tthhp xmhsbd vk vbrnf krsdgrm bmqh srmtb"
	" gvqdr vqjl jlpjdb jcr lqttkm kfxr gdbs ntft nmnfx jdvxf vshd nhx gfvfs bvb xdp fnngtqh kpjll ncqr r"
	"qjdcb rvnfcrr dlcgqg lsnrh vfrrd vmks dsphl vtdf cqvc gbhqd lrgd rzzt zkhfkg chbtp ksm dcqqd (contai"
	"ns peanuts, nuts)\nkrsdgrm bnl ncqr jzjc vmks vtdf gsq vmkt cqvc mbcx zkhfkg tmxm rrjb jdvxf mmnx xd"
	"p vnbrhb xzhxj ptpqnl lmnbtpn xhghxjg jjfhf xmhsbd gfvfs dlcgqg lkr fklqd qbdjjt jvv bjslhf zpkl sjf"
	"t mnlcj ckknl dsphl sbvbzcg fpd bkkhrl lcnxpz chbtp gcxjz rnqh dsjxr rdqs xnhbrx kfxr mzjnsm vfktc l"
	"snrh ntft (contains peanuts, nuts)\nxzhxj qzckbb kfxr jjrm lfxzl sbvbzcg pkvx fxhts dmssm vshd xlkf "
	"gbhqd bqtdv xtd qjzq ksm ttqqvb pnlkl xhghxjg trls cbxrs lch vcngs jsqpt bnl njdq dsphl vdqtnr ncqr "
	"fpd lcnxpz bjslhf vmks clbzn xjkpm sjft xhnl lgn vfcrdm dnprvn cghj vfrrd vtdf ptpqnl vbrnf dlcgqg s"
	"tttxbm fpbqsb rxvzb jzjc kkbbb zlkvkzt vsssd mbsc tthhp rzzt ckknl jsjz vqjl pmlqgp nhx vqgcbr gdvfs"
	"d mbcx mmnx sndbnc rrjb cqvc dsjxr zpkl bbqs bkkhrl chbtp xmhsbd dvnbt zmp tdtfnv jvv (contains whea"
	"t, peanuts, shellfish)\nxmhsbd gdvkh pkvx xdp lcnxpz rrjb dsjxr rvnfcrr dmssm frgmd hzhzkn mftbj xgh"
	"fgf rxvzb qnqg cdhlqp kqbkb dnprvn hdzcch rtzcq xxrzn gdvfsd hchrm mnlcj xlkf mzjnsm nhx fklqd lbnss"
	"cn kfxr gzhzhrc chbtp vk cqvc stttxbm fsbn dcqqd jkxsgpk kvzhn ptpqnl krsdgrm rdqs dsphl lkck jcr tt"
	"hhp jjfhf zpkl sxjxjx jdvxf fhcmcth sjft ntft ttqqvb jdrvf srmtb sndbnc pvzhm (contains peanuts, ses"
	"ame, fish)\nnhx ntft qdsp xnsxv rrjb xzhxj vmkt pmlqgp lch jkxsgpk fchcj xkmfx lkck tdtfnv fklqd rvn"
	"fcrr tmxm phgcp jdvxf svqkg ttqqvb dmrvf mbsc vshd kvzhn gdvkh cdqt fjbbj sndbnc ljxsf qbdjjt kfxr v"
	"tffks kpjll njdq dnprvn xmhsbd vcngs xjkpm flhn zpkl srbhb frgmd ptpqnl ntrqq vfrrd jvv mbcx cbxrs n"
	"pgxl jcr vqgcbr plgsn dcqqd jjfhf xhnl qdt chbtp jdmvk hzhzkn psqkpr vnbrhb pnlkl vmks hdgrmv vk fpd"
	" jlpjdb qzckbb gvqdr bbkq (contains fish, eggs, soy)\nxnhbrx bqprv kkbbb jjrm ptpqnl gdbs stpzhrp nj"
	"dq qnqg lkr vtffks cdhlqp mzjnsm xlkf gsq bbqs chbtp nhx qzckbb hchrm vk xtd qbmg plgsn jvv pvzhm xz"
	"hxj ckknl gcxjz vdqtnr vfrrd ggbpln ncqr rrjb npkvt ntpnb jdvxf vqjl xkmfx xmhsbd srmtb kfxr lrgd cq"
	"vc mftbj gzfm lmnbtpn bnl fxhts rqjdcb ssxljz srbhb npgxl tdtfnv gbhqd tmxm cghj ljjl xjkpm (contain"
	"s peanuts, nuts)\nxkmfx bbqs ntft tmxm gsq mnlcj jjrm njdq dsphl vnbrhb bkkhrl bmqh lkck ttqqvb jdrv"
	"f pnlkl lch jsjz kpjll rhzjdcjz cqvc dnprvn kqbkb rqjdcb chbtp flhn fchcj sndbnc qbmg ntpnb phgcp bl"
	"dts lcnxpz rzzt bzrtth kfxr rlmv kkbbb dsjxr mmnx zmp xzhxj ncxd vfktc rrjb sshkphb ggbpln cqfld jkx"
	"sgpk mftbj sbvbzcg sxjxjx mbsc krsdgrm psqkpr xnsxv rvnfcrr jsqpt vqjl ksm vmkt gdvfsd frgmd vsssd p"
	"lgsn zbm mbcx qxqngjh srmtb jcr jzjc sjft cdqt xmhsbd qnqg dmrvf stpzhrp (contains wheat, soy)\nqdt "
	"pmlqgp pvzhm lcnxpz dhtbh lqxt vfktc gdvfsd jdmvk lbnsscn jsqpt fpd bnl chbtp ckknl lkr mzjnsm jxrs "
	"rrjb rqjdcb vqgcbr qrt rxvzb vfcrdm xnsxv jzjc hchrm vtffks vshd gcxjz xxrzn dlcgqg npkvt sjft fjbbj"
	" jjfhf lrgd bvb srmtb pnlkl fnngtqh qbdjjt rhzjdcjz hzhzkn pkvx rvnfcrr xzhxj cqvc tbjh nhx zctbc np"
	"gxl mbcx ntft frgmd jfmvtdd xdp vmks cqfld gzfm gdnkc xhghxjg kfxr zpkl qdsp xjkpm rvpgl dsphl (cont"
	"ains shellfish, eggs)\nsvqkg gfvfs gdvfsd vtdf hdgrmv sndbnc dmssm rlmv jdvxf lrgd rdqs mqb lkck dsp"
	"hl cdqt vbrnf mzjnsm dvnbt qdsp lmnbtpn xhghxjg xmhsbd gdnkc kfxr qdt gzfm vk flhn vfktc ljxsf rrjb "
	"ntpnb rqjdcb sxjxjx ntft zctbc hchrm fjbbj xdp ptpqnl chbtp jvv npgxl cqvc qbmg vjmrl hzhzkn sbvbzcg"
	" njdq kvzhn stttxbm dhtbh plgsn pnlkl bldts ggbpln bqvr ttqqvb kkbbb bzrtth tbjh lfxzl cghj sshkphb "
	"ncxd vtffks hdzcch pkvx jsqpt ntrqq dlcgqg fpbqsb bkkhrl xzhxj vmjjv ncqr mmnx vfrrd psqkpr fklqd vq"
	"jl cdhlqp (contains shellfish)\nggbpln lgn ntft bqvr xhnl dsjxr xnhbrx vqjl tdtfnv chbtp dhtbh dvnbt"
	" npgxl cdqt jjrm cqvc ntrqq fxg bvb gdbs nhx mmnx gcxjz vtdf mqb dmrvf rhzjdcjz vcngs xhghxjg flhn f"
	"xhts mbcx fjbbj hdzcch jlpjdb rtxkp kcrh rrjb jkxsgpk rtzcq jxrs bldts vshd vnbrhb mml pmlqgp hzhzkn"
	" xmhsbd vmks ljjl rqjdcb bkkhrl plgsn bbqs qlrjf tthhp bqtdv lqttkm sjft dcqqd kfxr bnl lfxzl fpd zl"
	"kvkzt sbvbzcg zmp cqfld qrt rkgjkvl ksm jfmvtdd lhfj mbsc xxrzn vfcrdm tmxm vmjjv (contains soy)\nrt"
	"xkp jjfhf srmtb npgxl gdbs jdmvk mmnx jxrs dnprvn qrt xdp rrjb npkvt dsjxr xmhsbd zctbc vtdf cqvc fx"
	"g rsbph mnlcj cghj lqttkm dlcgqg ntft qjzq xjkpm mbsc xnsxv bkkhrl rhzjdcjz fxhts gzhzhrc zmp kcrh q"
	"bmg nmnfx jcr xhnl vtffks ntrqq rqjdcb zlkvkzt ncxd njdq lgn psqkpr cdhlqp vfktc tthhp bmqh jlpjdb s"
	"vqkg lch jfmvtdd bqprv ljxsf vqgcbr vfcrdm bqtdv vnbrhb tdtfnv pnlkl lcnxpz srbhb nhx lbnsscn sbvbzc"
	"g cbxrs fnngtqh dsphl pkvx lqxt jsjz cdqt qdt xkmfx kqbkb vcngs gdvkh rvpgl chbtp dvnbt vshd bqvr xz"
	"hxj zbm rtzcq vfrrd fhcmcth (contains wheat, shellfish)\nqnqg pnlkl dlcgqg fxhts xxrzn bmqh ntft xns"
	"xv cqvc plgsn xmhsbd kfxr vcngs bnl bqvr rtzcq mmnx lqttkm nhx lch bldts jjrm dsjxr gzfm mftbj xzhxj"
	" vtdf njdq vmks lbnsscn jjfhf bqtdv tthhp chbtp xghfgf flhn npgxl qxqngjh cbxrs rzzt kkbbb jfmvtdd l"
	"cnxpz vmkt cqfld vfrrd fklqd (contains fish)\nrrjb tdtfnv sbvbzcg dmrvf lmnbtpn trls gcxjz flhn hdgr"
	"mv jsqpt ncqr rnqh lch lrgd qnqg pnlkl jzjc gdvkh sxjxjx fpd xxrzn ncxd krsdgrm sshkphb lhfj xnsxv t"
	"mxm lqttkm xtd gvqdr kkbbb lsnrh srmtb xzhxj rxvzb bbqs tbjh tthhp nhx rvnfcrr ntft lkr cdhlqp kfxr "
	"vfktc fnngtqh kvzhn chbtp qjzq mnlcj qbmg xkmfx gsq pmlqgp cbxrs jdmvk bqtdv svqkg rtzcq vsssd clbzn"
	" npgxl vfrrd vtffks nmnfx lbnsscn rsbph vmks dvnbt qlrjf phgcp fxg bqprv lcnxpz ssxljz rvpgl gzfm sn"
	"dbnc vqgcbr cqvc (contains soy, nuts, sesame)\nxtd kkbbb ssxljz qbdjjt trls lkr bmqh ksm flhn vmkt g"
	"zfm rhzjdcjz psqkpr nhx jvv ckknl vqjl fklqd dmrvf lqxt zctbc gbhqd mzjnsm vjmrl rrjb nmnfx vfrrd ds"
	"phl bnl cqvc rtxkp vtdf xzhxj cdhlqp lsnrh srbhb bzrtth zbm cdqt mqb bjslhf fxhts mbcx xmhsbd lhfj f"
	"rgmd ntft dmssm fpbqsb zmp mml jxrs bqtdv jdrvf tdtfnv mmnx xghfgf jjrm qdt zpkl jsjz tbjh xxrzn fpd"
	" lch bqvr gcxjz plgsn jcr kfxr rtzcq jlpjdb rnqh (contains wheat, peanuts, eggs)\nchbtp krsdgrm bjsl"
	"hf sndbnc mzjnsm qrt gzhzhrc zmp cqvc cghj rtxkp xxrzn xlkf tbjh ntft rsbph xhnl vfcrdm vnbrhb nhx j"
	"cr qdt jsqpt rvnfcrr kqbkb vmkt qjzq fklqd vtdf ncxd rqjdcb lrgd lch vqgcbr bqtdv rlmv kfxr pkvx xdp"
	" ggbpln cdhlqp xnsxv fnngtqh dhtbh stttxbm ckknl vqjl qlrjf psqkpr rnqh bldts dlcgqg lqttkm qdsp qbm"
	"g gsq qnqg zkhfkg trls njdq mftbj gdvfsd fhcmcth rkgjkvl cbxrs stpzhrp hdzcch qbdjjt fchcj jjrm mnlc"
	"j zctbc ntrqq vcngs cdqt xtd rzzt jxrs xzhxj xmhsbd (contains wheat, soy, eggs)";
static const unsigned int input_len = 11752;
